import os
from dotenv import load_dotenv
from azure.cosmos import CosmosClient

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
endpoint = os.getenv("AZURE_COSMOS_ENDPOINT")
key = os.getenv("AZURE_COSMOS_KEY")
client = CosmosClient(endpoint, credential=key)
db = client.get_database_client(os.getenv("AZURE_COSMOS_DATABASE", "aceit"))
container = db.get_container_client("jupas_programmes")

programme = {
    "code": "JS6688",
    "nameEn": "Science Master Class",
    "nameZh": "科研專才啟導課程",
    "name": "Science Master Class",
    "university": "香港大學",
    "faculty": "理學院",
    "median": 34,
    "band_a": 32,
    "uq": 36,
    "category": "science"
}

en_admission = [
    "**JUPAS Code:** JS6688 | **University:** The University of Hong Kong (HKU)",
    "**Programme:** Science Master Class (SMC) — BSc & MRes Double Degree | **Faculty:** Faculty of Science",
    "**Duration:** 4.5–5 years (full-time) | **First Year Intake:** 26 students",
    "**Funding:** UGC-funded",
    "",
    "**Minimum DSE Entry Requirements:**",
    "- Chinese Language: Level 3",
    "- English Language: Level 3",
    "- Mathematics (Compulsory Part): Level 4",
    "- Citizenship and Social Development: Attained",
    "- Two Elective Subjects: BOTH must be science subjects at Level 3:",
    "  - Biology AND Chemistry, OR",
    "  - Biology AND Physics, OR",
    "  - Chemistry AND Physics, OR",
    "  - One science (Biology/Chemistry/Physics) AND M1/M2 at Level 3",
    "",
    "**Subject Weighting:** Biology, Chemistry, Physics, and M1/M2 are weighted at 1.2x in score calculation.",
    "",
    "**Scoring Formula:** Category A subjects and M1/M2 only (with 1.2x weighting for science subjects and M1/M2)",
    "",
    "**Interview:** Yes — conducted on a selective basis.",
    "",
    "**Academic Progression Requirement:** Students must maintain a high CGPA to remain in the double degree programme; otherwise, they will be required to transfer to the 6901 BSc programme.",
    "",
    "**2025 Admission Statistics:**",
    "- Band A applicants: 107",
    "- Total applicants: 491",
    "- Offers made: 20 (100% from Band A)",
    "",
    "**Admissions Scores (2025 admitted students):**",
    "- Median: 34 points",
    "- Upper Quartile (UQ): 36 points",
    "- Lower Quartile (LQ): 32 points"
]

en_curriculum = [
    "The Science Master Class is an **elite double degree programme** combining a Bachelor of Science (BSc) and a Master of Research (MRes), designed for highly able science students who aspire to become research scientists.",
    "",
    "**Programme Structure:**",
    "- **Total Credits:** 303 credits (240 BSc + 63 MRes)",
    "- **Duration:** 4.5–5 years (accelerated fast-track)",
    "",
    "**Year 1:**",
    "- Basic science courses (42 credits)",
    "- Non-credit bearing requirements",
    "- Foundation in chosen intensive major",
    "",
    "**Year 2:**",
    "- Intensive major courses (72 credits)",
    "- Special tutorials by Grand Masters (exclusive to SMC students)",
    "- Research ethics course (3 credits)",
    "",
    "**Year 3:**",
    "- Advanced major courses (60 credits)",
    "- Research postgraduate courses (18 credits)",
    "- Elective courses (48–54 credits)",
    "- Transferable skills training",
    "",
    "**Year 4:**",
    "- Free electives and research preparation (36 credits)",
    "- Summer Research Fellowship (SRF)",
    "- Overseas Research Fellowship (ORF) opportunities",
    "",
    "**Year 4 Summer / Year 5 Semester 1:**",
    "- MRes research project (42 credits)",
    "- Complete research project for MRes degree",
    "",
    "**Intensive Majors Available:**",
    "- Biological Sciences (Intensive)",
    "- Ecology & Biodiversity (Intensive)",
    "- Molecular Biology & Biotechnology (Intensive)",
    "- Chemistry (Intensive)",
    "- Mathematics (Intensive)",
    "- Physics (Intensive)",
    "- Geology (Intensive)",
    "",
    "**Unique Features:**",
    "- **Science Masters as Academic Advisers:** Renowned scientists including Members of Chinese Academy of Sciences, Hong Kong Academy of Sciences, and international award winners",
    "- **Grand Masters Special Tutorials:** Exclusive tutorials by world-class scientists including Nobel Laureates",
    "- **Young Scientist Scheme (YSS):** Summer Research Fellowship, Overseas Research Fellowship, entrance scholarships, and exchange study opportunities",
    "- **Research-Immersion Environment:** Authentic research training from Year 1"
]

en_career = [
    "Science Master Class graduates are uniquely positioned for careers in scientific research, academia, and technology innovation.",
    "",
    "**Career Pathways:**",
    "",
    "**1. Research & Academia**",
    "- Pursue PhD at prominent universities overseas or at HKU",
    "- Join research institutes as research scientists",
    "- Academic positions at universities",
    "",
    "**2. Biotechnology & Pharmaceutical Industries**",
    "- R&D roles in biotech and pharma companies",
    "- Drug discovery and development",
    "- Clinical research",
    "",
    "**3. Technology & Innovation**",
    "- Data science and AI research",
    "- Technology startups",
    "- Innovation-driven enterprises",
    "",
    "**4. Government & Public Sector**",
    "- Government research laboratories",
    "- Policy advisory roles",
    "- Environmental and conservation agencies",
    "",
    "**5. Professional Services**",
    "- Some intensive majors fulfil accreditation requirements of UK professional societies",
    "- Accelerated route to professional qualifications",
    "",
    "**Further Studies:**",
    "- PhD in science disciplines (well-prepared through MRes training)",
    "- Postdoctoral research positions",
    "- Professional master's programmes"
]

en_campus = [
    "**Campus & Facilities:**",
    "- Based at HKU's Main Campus in Pok Fu Lam",
    "- State-of-the-art laboratories and research facilities",
    "- Access to HKU's world-class research infrastructure",
    "",
    "**Student Life:**",
    "- Small elite cohort of approximately 26 students",
    "- Close interaction with Science Masters and Grand Masters",
    "- Research interest groups and journal clubs",
    "- Cross-disciplinary collaboration opportunities",
    "- International exchange and research fellowship opportunities",
    "",
    "**Research Opportunities:**",
    "- Summer Research Fellowship (SRF) after Year 3",
    "- Overseas Research Fellowship (ORF) at international institutions",
    "- Research projects starting from Year 1",
    "- Access to HKU's research laboratories and equipment",
    "",
    "**Notable Faculty (Grand Masters):**",
    "- **Professor Ferenc Krausz** — 2023 Nobel Laureate in Physics, pioneer in attosecond science",
    "- **Professor Chi Ming CHE** — Member of Chinese Academy of Sciences, First-class Prize of State Natural Science Award",
    "- **Professor Vivian Wing Wah YAM** — International Member of US National Academy of Sciences",
    "- **Professor Ngaiming MOK** — Renowned mathematician",
    "- **Professor Hongjie DAI** — Highly cited scientist in materials science",
    "- **Professor Wang YAO** — New Cornerstone Investigator in condensed matter physics"
]

en_competitiveness = [
    "**Admission Competitiveness Analysis:**",
    "",
    "**Competition Level:** VERY HIGH — 5.4 Band A applicants per offer (107 Band A ÷ 20 offers)",
    "",
    "**Key Statistics (2025):**",
    "- Total applicants: 491 (up from 460 in 2024)",
    "- Band A applicants: 107 (up from 105 in 2024)",
    "- Offers: 20 (down from 25 in 2024)",
    "- 100% of offers go to Band A applicants",
    "",
    "**Score Analysis:**",
    "- Median: 34 points (with 1.2x science subject weighting)",
    "- The 1.2x weighting for science subjects means strong science students are rewarded",
    "- Math Compulsory Part Level 4 is a higher requirement than standard programmes",
    "",
    "**Critical Success Factors:**",
    "1. **Band A placement is ESSENTIAL** — 100% of offers go to Band A",
    "2. **Two science electives required** — Must have Biology, Chemistry, or Physics at Level 3+",
    "3. **Math Level 4** — Higher than standard requirement; filters out many applicants",
    "4. **Strong science grades** — With 1.2x weighting, Level 5+ in science subjects significantly boosts your score",
    "5. **Research aptitude** — Demonstrated interest in scientific research through competitions, projects, or internships",
    "6. **Interview performance** — Selective interviews assess scientific thinking and research potential",
    "7. **Academic resilience** — Must maintain high CGPA; programme is demanding and not all students complete the double degree"
]

en_alumni = [
    "**About the Science Master Class:**",
    "",
    "The Science Master Class is HKU Faculty of Science's flagship elite programme, launched in 2021. It incubates the next generation of scientists through an accelerated double degree pathway.",
    "",
    "**Faculty Excellence:**",
    "- HKU Science is ranked #11 in World University Rankings 2026",
    "- #1 in Asia University Rankings",
    "- World-class faculty including Nobel Laureates and academy members",
    "",
    "**Research Infrastructure:**",
    "- State Key Laboratory of Synthetic Chemistry",
    "- Laboratory for Synthetic Chemistry & Chemical Biology",
    "- Advanced materials and nanotechnology facilities",
    "- High-performance computing resources",
    "",
    "**Global Recognition:**",
    "- HKU ranked #10 in World Graduate Employability Ranking",
    "- #3 in Most International Universities",
    "- Strong international research collaborations"
]

en_scholarships = [
    "**Science Master Class Scholarships:**",
    "",
    "**Young Scientist Scheme (YSS) Entrance Scholarship:**",
    "- For outstanding SMC entrants",
    "- Supports research activities and academic development",
    "",
    "**HKU Entrance Scholarships:**",
    "- **HKU Foundation Entrance Scholarship** — For outstanding JUPAS applicants",
    "- **HKU Outstanding Students Scholarship** — For students with all 5** in core and elective subjects",
    "",
    "**Research Fellowships:**",
    "- **Summer Research Fellowship (SRF)** — Funded summer research projects",
    "- **Overseas Research Fellowship (ORF)** — International research placements",
    "",
    "**Government Financial Aid:**",
    "- Tertiary Student Finance Scheme (TSFS) — Means-tested grant and loan",
    "- Non-means-tested Loan Scheme (NLS) — Low-interest loan for all eligible students",
    "",
    "**Other Opportunities:**",
    "- Exchange study scholarships",
    "- Research conference travel grants",
    "- Industry-sponsored research prizes"
]

en_tips = [
    "**Ace Sir's HKU Science Master Class Strategy — 9 Actionable Tips:**",
    "",
    "**1. Band A is Mandatory**",
    "100% of offers go to Band A applicants. If SMC is your dream, you MUST place JS6688 in Band A.",
    "",
    "**2. Excel in Two Science Subjects**",
    "You need TWO science electives (Bio/Chem/Physics) at Level 3+, or one science + M1/M2. With 1.2x weighting, strong science grades give you a massive advantage. Aim for Level 5+ in both science subjects. Chemistry + Biology is the most versatile combination.",
    "",
    "**3. Math Level 4 is Your First Filter**",
    "Most science programmes require Math Level 2. SMC requires Level 4 — this immediately filters out many applicants. Ensure your math fundamentals are rock-solid. M1/M2 is highly recommended and counts as a science subject.",
    "",
    "**4. Target 34+ Points (with Weighting)**",
    "The median is 34 points with 1.2x science weighting. To calculate: if you have Chemistry Level 5 (5.5 × 1.2 = 6.6) and Biology Level 5 (5.5 × 1.2 = 6.6), that's already 13.2 points from just two subjects. Aim for consistent Level 4–5 across all subjects.",
    "",
    "**5. Demonstrate Research Passion**",
    "SMC is for research-aspired students. Build evidence:",
    "- Participate in science competitions (HKSTPC, Biology Olympiad, Chemistry Olympiad)",
    "- Undertake a science research project (e.g., school-based, summer programme)",
    "- Read scientific papers and journals (Nature, Science)",
    "- Attend science lectures or webinars",
    "- Shadow a researcher at a university lab",
    "",
    "**6. Prepare for the Selective Interview**",
    "Not all applicants are interviewed. If selected, expect:",
    "- 'Why research? Why not just BSc?' (Have a genuine answer)",
    "- Discussion of a scientific topic you're passionate about",
    "- Problem-solving questions testing scientific thinking",
    "- Your understanding of what MRes entails",
    "- Questions about your long-term career goals in science",
    "",
    "**7. Understand the Academic Demands**",
    "SMC is NOT an easy path. Key realities:",
    "- 303 credits in 4.5–5 years (standard BSc is 240 credits in 4 years)",
    "- Must maintain high CGPA or transfer to standard BSc (6901)",
    "- Intensive research training from Year 1",
    "- MRes research project in Year 4 Summer/Year 5",
    "- Only join if you're genuinely passionate about research",
    "",
    "**8. Choose Your Intensive Major Wisely**",
    "SMC offers 7 intensive majors. Consider:",
    "- Your strongest science subject (where you can achieve highest grades)",
    "- Research interests (which field excites you most?)",
    "- Career goals (academia, industry, biotech, etc.)",
    "- Some majors have professional accreditation pathways",
    "",
    "**9. Have a Backup Plan**",
    "With only 20 offers and 107 Band A applicants, admission is tough. Consider:",
    "- HKU BSc (JS6901) — same faculty, more places, can still do research",
    "- HKUST Science or Engineering — strong research focus",
    "- CUHK Science — excellent research opportunities",
    "- Remember: If you join SMC but don't maintain CGPA, you'll transfer to BSc anyway"
]

zh_admission = [
    "**JUPAS 編號：** JS6688 | **大學：** 香港大學",
    "**課程：** 科研專才啟導課程 (Science Master Class) — 理學士及研究碩士雙學位 | **學院：** 理學院",
    "**修讀年期：** 4.5–5年（全日制）| **首年學額：** 26人",
    "**資助類別：** 教資會資助",
    "",
    "**最低 DSE 入學要求：**",
    "- 中國語文：第3級",
    "- 英國語文：第3級",
    "- 數學（必修部分）：第4級",
    "- 公民與社會發展：達標",
    "- 兩科選修科目：均須為理科科目，達第3級：",
    "  - 生物及化學，或",
    "  - 生物及物理，或",
    "  - 化學及物理，或",
    "  - 一科理科（生物／化學／物理）及 M1/M2",
    "",
    "**科目權重：** 生物、化學、物理及 M1/M2 在計分時加權 1.2倍。",
    "",
    "**計分方法：** 甲類科目及 M1/M2（理科科目及 M1/M2 加權 1.2倍）",
    "",
    "**面試安排：** 設有選擇性面試。",
    "",
    "**學業進展要求：** 學生須保持高累積平均積點（CGPA）以繼續修讀雙學位課程；否則須轉至 6901 理學士課程。",
    "",
    "**2025年入學統計：**",
    "- Band A 申請人數：107人",
    "- 總申請人數：491人",
    "- 錄取名額：20人（100%來自 Band A）",
    "",
    "**2025年入學分數（已獲錄取學生）：**",
    "- 中位數：34分",
    "- 上四分位數：36分",
    "- 下四分位數：32分"
]

zh_curriculum = [
    "科研專才啟導課程是專為高能力理科學生而設的 **精英雙學位課程**，結合理學士（BSc）及研究碩士（MRes），旨在培育未來科研人才。",
    "",
    "**課程結構：**",
    "- **總學分：** 303學分（240學分 BSc + 63學分 MRes）",
    "- **修讀年期：** 4.5–5年（加速 fast-track）",
    "",
    "**第一年：**",
    "- 基礎科學課程（42學分）",
    "- 非學分要求",
    "- 選定精研主修的基础",
    "",
    "**第二年：**",
    "- 精研主修課程（72學分）",
    "- 大師級導師專屬教程（SMC 學生獨享）",
    "- 研究倫理課程（3學分）",
    "",
    "**第三年：**",
    "- 高階主修課程（60學分）",
    "- 研究式研究生課程（18學分）",
    "- 選修課程（48–54學分）",
    "- 可轉移技能培訓",
    "",
    "**第四年：**",
    "- 自由選修及研究準備（36學分）",
    "- 暑期研究獎學金（SRF）",
    "- 海外研究獎學金（ORF）機會",
    "",
    "**第四年暑假／第五年第一學期：**",
    "- MRes 研究項目（42學分）",
    "- 完成研究碩士學位論文",
    "",
    "**精研主修選擇：**",
    "- 生物科學（精研）",
    "- 生態學及生物多樣性（精研）",
    "- 分子生物學及生物科技（精研）",
    "- 化學（精研）",
    "- 數學（精研）",
    "- 物理（精研）",
    "- 地質學（精研）",
    "",
    "**獨特特色：**",
    "- **科學大師擔任學術導師：** 包括中國科學院院士、香港科學院院士及國際獎項得主",
    "- **大師級專屬教程：** 由諾貝爾獎得主等世界級科學家親授",
    "- **青年科學家計劃（YSS）：** 暑期研究獎學金、海外研究獎學金、入學獎學金及交流機會",
    "- **研究沉浸環境：** 從第一年起接受真實研究培訓"
]

zh_career = [
    "科研專才啟導課程畢業生於科學研究、學術界及科技創新領域具獨特優勢。",
    "",
    "**就業出路：**",
    "",
    "**1. 研究及學術界**",
    "- 於海外知名大學或港大修讀博士",
    "- 加入研究機構成為研究科學家",
    "- 大學學術職位",
    "",
    "**2. 生物科技及製藥工業**",
    "- 生物科技公司研發職位",
    "- 藥物發現及開發",
    "- 臨床研究",
    "",
    "**3. 科技及創新**",
    "- 數據科學及人工智能研究",
    "- 科技初創企業",
    "- 創新驅動企業",
    "",
    "**4. 政府及公共部門**",
    "- 政府研究實驗室",
    "- 政策顧問職位",
    "- 環境及保育機構",
    "",
    "**5. 專業服務**",
    "- 部分精研主修符合英國專業學會認可要求",
    "- 加速取得專業資格途徑",
    "",
    "**進修途徑：**",
    "- 科學領域博士課程（透過 MRes 培訓充分準備）",
    "- 博士後研究職位",
    "- 專業碩士課程"
]

zh_campus = [
    "**校園及設施：**",
    "- 設於港大本部校園（薄扶林）",
    "- 先進實驗室及研究設施",
    "- 可使用港大世界級研究基建",
    "",
    "**學生生活：**",
    "- 每年約26人的精英小班",
    "- 與科學大師及大師級導師緊密互動",
    "- 研究興趣小組及期刊會",
    "- 跨學科合作機會",
    "- 國際交流及研究獎學金機會",
    "",
    "**研究機會：**",
    "- 第三年後暑期研究獎學金（SRF）",
    "- 海外研究獎學金（ORF）於國際機構",
    "- 從第一年起參與研究項目",
    "- 使用港大研究實驗室及設備",
    "",
    "**知名教職員（大師級導師）：**",
    "- **Krausz 教授** — 2023年諾貝爾物理學獎得主，阿秒科學先驅",
    "- **支志明教授** — 中國科學院院士，國家自然科學獎一等獎得主",
    "- **任詠華教授** — 美國國家科學院外籍院士",
    "- **莫毅明教授** — 著名數學家",
    "- **戴宏杰教授** — 材料科學高被引科學家",
    "- **姚望教授** — 凝聚態物理學新基石研究員"
]

zh_competitiveness = [
    "**入學競爭力分析：**",
    "",
    "**競爭程度：** 極高 — 每個學額有5.4位 Band A 申請者（107人 ÷ 20個名額）",
    "",
    "**主要數據（2025年）：**",
    "- 總申請人數：491人（較2024年的460人增加）",
    "- Band A 申請人數：107人（較2024年的105人增加）",
    "- 錄取名額：20人（較2024年的25人減少）",
    "- 100%錄取來自 Band A",
    "",
    "**分數分析：**",
    "- 中位數：34分（理科科目加權 1.2倍後）",
    "- 1.2倍理科加權意味理科成績強的學生獲優勢",
    "- 數學必修部分第4級要求高於一般課程",
    "",
    "**成功入讀的關鍵因素：**",
    "1. **必須放 Band A** — 100%錄取來自 Band A",
    "2. **必須修讀兩科理科選修** — 生物、化學或物理須達第3級或以上",
    "3. **數學必修部分第4級** — 高於一般要求，已篩走不少申請者",
    "4. **理科成績出色** — 1.2倍加權下，理科達第5級可大幅提升分數",
    "5. **研究潛質** — 透過比賽、項目或實習展示對科研的興趣",
    "6. **面試表現** — 選擇性面試評估科學思維及研究潛力",
    "7. **學術韌力** — 須保持高 CGPA；課程要求高，並非所有學生都能完成雙學位"
]

zh_alumni = [
    "**關於科研專才啟導課程：**",
    "",
    "科研專才啟導課程是港大理學院的旗艦精英課程，2021年推出。透過加速雙學位途徑培育下一代科學家。",
    "",
    "**學院卓越：**",
    "- 港大理學院於2026年世界大學排名第11位",
    "- 亞洲大學排名第1位",
    "- 世界級教職員包括諾貝爾獎得主及院士",
    "",
    "**研究基建：**",
    "- 合成化學國家重點實驗室",
    "- 合成化學與化學生物學實驗室",
    "- 先進材料及納米科技設施",
    "- 高效能運算資源",
    "",
    "**國際認可：**",
    "- 港大於世界畢業生就業力排名第10位",
    "- 國際化大學排名第3位",
    "- 強大的國際研究合作網絡"
]

zh_scholarships = [
    "**科研專才啟導課程獎學金：**",
    "",
    "**青年科學家計劃（YSS）入學獎學金：**",
    "- 頒予傑出 SMC 入學者",
    "- 資助研究活動及學術發展",
    "",
    "**港大入學獎學金：**",
    "- **港大基金入學獎學金** — 頒予 DSE 成績卓越的 JUPAS 申請人",
    "- **港大傑出學生獎學金** — 頒予核心科目及選修科目均獲5**的學生",
    "",
    "**研究獎學金：**",
    "- **暑期研究獎學金（SRF）** — 資助暑期研究項目",
    "- **海外研究獎學金（ORF）** — 國際研究實習",
    "",
    "**政府資助：**",
    "- 專上學生資助計劃（TSFS）— 經入息審查的助學金及貸款",
    "- 免入息審查貸款計劃（NLS）— 所有合資格學生均可申請的低息貸款",
    "",
    "**其他機會：**",
    "- 交流學習獎學金",
    "- 研究會議旅費資助",
    "- 業界贊助研究獎項"
]

zh_tips = [
    "**Ace Sir 港大科研專才啟導課程攻略 — 9個實戰貼士：**",
    "",
    "**1. 必須放 Band A**",
    "100%錄取來自 Band A 申請者。若 SMC 是你的夢想，必須將 JS6688 放在 Band A。",
    "",
    "**2. 兩科理科選修要出色**",
    "你需要兩科理科選修（生物／化學／物理）達第3級或以上，或一科理科 + M1/M2。1.2倍加權下，強大理科成績帶來巨大優勢。建議兩科理科均目標第5級或以上。化學 + 生物是最靈活的組合。",
    "",
    "**3. 數學必修部分第4級是第一道關卡**",
    "大部分理科課程要求數學第2級，SMC 要求第4級 — 這已篩走不少申請者。確保數學基礎穩固。強烈建議修讀 M1/M2，既可計算為理科選修，又能增強研究所需的量化能力。",
    "",
    "**4. 目標34分或以上（加權後）**",
    "中位數為34分（理科 1.2倍加權後）。例如：化學第5級（5.5 × 1.2 = 6.6）及生物第5級（5.5 × 1.2 = 6.6），僅兩科已達13.2分。建議各科保持第4至5級的均衡成績。",
    "",
    "**5. 展示研究熱誠**",
    "SMC 專為有志科研的學生而設。建立證明：",
    "- 參與科學比賽（香港學生科學比賽、生物奧林匹克、化學奧林匹克）",
    "- 進行科學研究項目（校內或暑期計劃）",
    "- 閱讀科學論文及期刊（Nature、Science）",
    "- 參加科學講座或網上研討會",
    "- 於大學實驗室 shadow 研究者",
    "",
    "**6. 準備選擇性面試**",
    "並非所有申請者都獲面試機會。若被選中，預計會被問及：",
    "- 「為何選擇研究？為何不讀普通理學士？」（須有真誠答案）",
    "- 討論你熱衷的科學課題",
    "- 測試科學思維的解難題目",
    "- 你對 MRes 的理解",
    "- 長遠科學事業目標",
    "",
    "**7. 了解學術要求**",
    "SMC 不是輕鬆的路。現實考量：",
    "- 4.5–5年內完成303學分（普通理學士4年240學分）",
    "- 須保持高 CGPA，否則轉至普通理學士（6901）",
    "- 從第一年起接受密集研究培訓",
    "- 第四年暑假／第五年完成 MRes 研究項目",
    "- 只有真正熱愛研究才應加入",
    "",
    "**8. 明智選擇精研主修**",
    "SMC 提供7個精研主修。考慮因素：",
    "- 你最強的理科科目（能取得最高成績的）",
    "- 研究興趣（哪個領域最令你興奮？）",
    "- 事業目標（學術界、工業界、生物科技等）",
    "- 部分主修具專業認可途徑",
    "",
    "**9. 要有後備方案**",
    "只有20個學額，107位 Band A 申請者，入學競爭激烈。建議考慮：",
    "- 港大理學士（JS6901）— 同一學院，學額較多，仍可從事研究",
    "- 科大科學或工程 — 強大的研究重點",
    "- 中大理學院 — 卓越的研究機會",
    "- 記住：即使入讀 SMC 但未能保持 CGPA，亦會轉至理學士"
]

details = {
    "code": "JS6688",
    "university": "香港大學",
    "en": {
        "sections": {
            "admission": {"title": "Eligibility & Admission Criteria (DSE)", "content": en_admission},
            "curriculum": {"title": "Programme Structure & Curriculum", "content": en_curriculum},
            "career": {"title": "Career Pathways & Prospects", "content": en_career},
            "campus": {"title": "Campus Life & Student Experience", "content": en_campus},
            "competitiveness": {"title": "Admission Competitiveness Analysis", "content": en_competitiveness},
            "alumni": {"title": "Notable Alumni & Faculty", "content": en_alumni},
            "scholarships": {"title": "Scholarships & Financial Aid", "content": en_scholarships},
            "tips": {"title": "Ace Sir's HKU Science Master Class Strategy", "content": en_tips}
        }
    },
    "zh": {
        "sections": {
            "admission": {"title": "入學要求與計分詳情 (DSE)", "content": zh_admission},
            "curriculum": {"title": "課程結構與內容", "content": zh_curriculum},
            "career": {"title": "職業前景與出路", "content": zh_career},
            "campus": {"title": "校園生活與學生體驗", "content": zh_campus},
            "competitiveness": {"title": "入學競爭力分析", "content": zh_competitiveness},
            "alumni": {"title": "知名校友及教職員", "content": zh_alumni},
            "scholarships": {"title": "獎學金及經濟援助", "content": zh_scholarships},
            "tips": {"title": "Ace Sir 港大科研專才啟導課程攻略", "content": zh_tips}
        }
    }
}

container.upsert_item({**programme, "id": f"prog_{programme['code']}", "pk": "programmes", "type": "programme"})
container.upsert_item({**details, "id": f"detail_{details['code']}", "pk": "details", "type": "programme_detail"})
print(f"[Seed] {programme['code']} - {programme['nameEn']} / {programme['nameZh']} - Done!")
