import os
from dotenv import load_dotenv
from azure.cosmos import CosmosClient

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
endpoint = os.getenv("AZURE_COSMOS_ENDPOINT")
key = os.getenv("AZURE_COSMOS_KEY")
client = CosmosClient(endpoint, credential=key)
db = client.get_database_client(os.getenv("AZURE_COSMOS_DATABASE", "aceit"))
container = db.get_container_client("jupas_programmes")

programme = {
    "code": "JS6626",
    "nameEn": "Bachelor of Medicine and Bachelor of Surgery (Distinguished MedScholar)",
    "nameZh": "內外全科醫學士 - 傑出醫科學人",
    "name": "Bachelor of Medicine and Bachelor of Surgery (Distinguished MedScholar)",
    "university": "香港大學",
    "faculty": "醫學院",
    "median": 44,
    "band_a": 42,
    "uq": 47,
    "category": "medicine"
}

en_admission = [
    "**JUPAS Code:** JS6626 | **University:** The University of Hong Kong (HKU)",
    "**Programme:** Bachelor of Medicine and Bachelor of Surgery (Distinguished MedScholar) | **Faculty:** Li Ka Shing Faculty of Medicine",
    "**Duration:** 6 years (full-time) | **First Year Intake:** 300 places (combined with JS6456 MBBS)",
    "**Funding:** UGC-funded",
    "",
    "**Minimum DSE Entry Requirements:**",
    "- Chinese Language: Level 3",
    "- English Language: Level 4",
    "- Mathematics (Compulsory Part): Level 2",
    "- Citizenship and Social Development: Attained",
    "- Two Elective Subjects: Level 3 in BOTH, with one being Biology or Chemistry (or M1/M2 at Level 3 + Biology/Chemistry)",
    "",
    "**Additional Requirements:** A good working knowledge of Cantonese is required for clinical training.",
    "",
    "**Scoring Formula:** Best 6 subjects (Category A subjects and M1/M2 only)",
    "",
    "**Interview:** Yes — conducted on a selective basis. Individual interview (English and Chinese) and group interview (English).",
    "",
    "**Note:** This programme shares the same 300 intake places with JS6456 (MBBS). Students are admitted to the Distinguished MedScholar track based on academic excellence and interview performance.",
    "",
    "**Admissions Scores (2025 admitted students, combined with JS6456):**",
    "- Median: 44 points",
    "- Upper Quartile (UQ): 47 points",
    "- Lower Quartile (LQ): 42 points"
]

en_curriculum = [
    "The Distinguished MedScholar (DMS) track follows the same **6-year MBBS curriculum** as JS6456, with additional enrichment opportunities designed to nurture scholars of academic excellence.",
    "",
    "**Core MBBS Curriculum (same as JS6456):**",
    "- Years 1–2: Pre-clinical training (anatomy, physiology, biochemistry, pathology, pharmacology)",
    "- Years 3–5: Clinical rotations in medicine, surgery, paediatrics, obstetrics & gynaecology, psychiatry, and more",
    "- Year 6: Clinical electives, revision, and preparation for licensing examination",
    "",
    "**Distinguished MedScholar Exclusive Features:**",
    "",
    "**1. Enrichment Year (Year 3)**",
    "- DMS students undertake a Master of Research in Medicine (MRes[Med]) during their Enrichment Year",
    "- Research training under faculty supervision",
    "- Option to pursue other Bachelor's or Master's degree programmes during EY",
    "- Graduate with an extra degree in addition to MBBS within the normative 6-year study period",
    "",
    "**2. Elite Mentorship Programme**",
    "- Guaranteed elite mentorship from chosen mentors within the Faculty or the University",
    "- One-on-one guidance from leading medical researchers and clinicians",
    "- Career planning and academic development support",
    "",
    "**3. Academic Workshops & Community Projects**",
    "- Series of academic workshops to develop research and critical thinking skills",
    "- Community-based projects to foster compassion and social responsibility",
    "- Opportunities to engage with cutting-edge medical research",
    "",
    "**4. Guaranteed Hall Residence**",
    "- Guaranteed residential places in student halls",
    "- Hall fees covered by possible financial support from HKUMed",
    "",
    "**5. PhD Pathway Support**",
    "- Upon completion of MBBS, MRes[Med], and one-year internship, students receive financial support from the Faculty to pursue a PhD at a renowned university",
    "- Potential to join the Faculty as clinical academics upon PhD completion",
    "",
    "**Teaching Hospitals:**",
    "- Queen Mary Hospital (primary teaching hospital)",
    "- Other HKU-affiliated hospitals and clinics"
]

en_career = [
    "Graduates of the Distinguished MedScholar track have the same professional pathways as standard MBBS graduates, with additional academic and research opportunities.",
    "",
    "**Professional Registration:**",
    "- Eligible to sit for the Licensing Examination of the Medical Council of Hong Kong",
    "- Upon passing, registration as a medical practitioner in Hong Kong",
    "",
    "**Career Pathways:**",
    "1. **Clinical Practice** — Hospital Authority, private practice, or specialist training",
    "2. **Academic Medicine** — Join HKU or other universities as clinical academics (supported by PhD pathway)",
    "3. **Medical Research** — Lead research programmes with MRes[Med] and PhD training",
    "4. **Public Health & Policy** — Government health departments, WHO, NGOs",
    "5. **Medical Administration** — Hospital management, healthcare policy",
    "",
    "**DMS-Specific Advantages:**",
    "- Early exposure to research through MRes[Med] during Enrichment Year",
    "- Financial support for PhD studies at renowned international universities",
    "- Guaranteed mentorship from leading faculty members",
    "- Strong foundation for a career in academic medicine",
    "",
    "**Further Studies:**",
    "- PhD in Medicine or related fields (with Faculty financial support)",
    "- Specialist training in Hong Kong or overseas",
    "- Master's programmes in public health, medical education, or healthcare management"
]

en_campus = [
    "**Campus & Facilities:**",
    "- Based at HKU's Main Campus in Pok Fu Lam and Sassoon Road Medical Campus",
    "- State-of-the-art laboratories, dissection rooms, and clinical simulation centres",
    "- Queen Mary Hospital as the primary teaching hospital",
    "",
    "**Student Life (DMS-specific):**",
    "- Guaranteed hall residence with potential fee support",
    "- Close-knit community of high-achieving medical students",
    "- Access to exclusive academic workshops and seminars",
    "- Research interest groups and journal clubs",
    "- Community service projects organised specifically for DMS students",
    "",
    "**Enrichment Year Experience:**",
    "- Full year dedicated to research training (MRes[Med]) or another degree",
    "- Work alongside world-class researchers at HKU",
    "- Opportunity to publish research papers as an undergraduate",
    "- International research collaborations",
    "",
    "**Mentorship:**",
    "- Personal mentor chosen from Faculty professors or University scholars",
    "- Regular meetings for academic and career guidance",
    "- Networking opportunities with leading medical professionals"
]

en_competitiveness = [
    "**Admission Competitiveness Analysis:**",
    "",
    "**Competition Level:** EXTREMELY HIGH — Shares 300 places with JS6456 (MBBS)",
    "",
    "**Key Points:**",
    "- The Distinguished MedScholar track is for the most academically outstanding MBBS applicants",
    "- Same entry requirements and scoring as JS6456 (MBBS)",
    "- Admission to DMS is based on exceptional DSE results and outstanding interview performance",
    "- Students must demonstrate strong potential for academic research and leadership",
    "",
    "**Admissions Scores (combined with JS6456, 2025):**",
    "- Median: 44 points (Best 6 subjects)",
    "- Upper Quartile (UQ): 47 points",
    "- Lower Quartile (LQ): 42 points",
    "",
    "**DMS vs Standard MBBS:**",
    "- DMS students typically have stronger academic profiles than standard MBBS entrants",
    "- The DMS track is highly selective within the already competitive MBBS pool",
    "- Not all MBBS applicants are considered for DMS — it's by invitation based on merit",
    "",
    "**Critical Success Factors:**",
    "1. **Exceptional DSE results** — Aim for 45+ points in Best 6 to be competitive for DMS",
    "2. **Outstanding interview performance** — Demonstrate research interest, leadership potential, and academic curiosity",
    "3. **Strong SLP/OEA** — Evidence of research experience, academic competitions, leadership roles",
    "4. **Clear academic career vision** — Articulate why you want to pursue academic medicine",
    "5. **Band A placement** — Essential, same as standard MBBS"
]

en_alumni = [
    "**About the Distinguished MedScholar Programme:**",
    "",
    "The Distinguished MedScholar track is HKU Medical Faculty's flagship programme for nurturing future medical academics and research leaders. It combines the rigorous MBBS clinical training with advanced research education.",
    "",
    "**Faculty Leadership:**",
    "- Led by the Li Ka Shing Faculty of Medicine, one of Asia's premier medical schools",
    "- Mentorship from world-renowned researchers and clinicians",
    "- Access to HKU's extensive international research network",
    "",
    "**Research Excellence:**",
    "- HKU Medicine is ranked among the world's top medical faculties",
    "- Leading research in cancer, infectious diseases, neuroscience, and public health",
    "- State-of-the-art research facilities at the Sassoon Road campus",
    "",
    "**Notable Features:**",
    "- First medical school in Hong Kong (established 1887)",
    "- Strong tradition of producing medical leaders and academics",
    "- Extensive global partnerships with leading medical institutions"
]

en_scholarships = [
    "**Distinguished MedScholar Financial Support:**",
    "",
    "**Hall Residence Support:**",
    "- Guaranteed residential places in student halls",
    "- Hall fees covered by possible financial support from HKUMed",
    "",
    "**PhD Study Support:**",
    "- Financial support from the Faculty to pursue a PhD at a renowned university after completing MBBS, MRes[Med], and internship",
    "- Covers tuition and living expenses during PhD studies",
    "",
    "**HKU Entrance Scholarships:**",
    "- **HKU Foundation Entrance Scholarship** — For outstanding JUPAS applicants",
    "- **HKU Outstanding Students Scholarship** — For students with all 5** in core and elective subjects",
    "",
    "**Government Financial Aid:**",
    "- Tertiary Student Finance Scheme (TSFS) — Means-tested grant and loan",
    "- Non-means-tested Loan Scheme (NLS) — Low-interest loan for all eligible students",
    "",
    "**Other Opportunities:**",
    "- Research grants for MRes[Med] projects",
    "- Travel grants for international conferences",
    "- Overseas exchange scholarships"
]

en_tips = [
    "**Ace Sir's HKU Distinguished MedScholar Strategy — 9 Actionable Tips:**",
    "",
    "**1. Aim Higher Than Standard MBBS**",
    "DMS is the elite track within MBBS. While standard MBBS median is 44, DMS students typically score higher. Aim for 45+ in Best 6 subjects to be competitive.",
    "",
    "**2. Demonstrate Research Interest Early**",
    "DMS is designed for future academic physicians. Show evidence of:",
    "- Participation in science research competitions (e.g., HKSTPC, ISEF)",
    "- Research internships at universities or hospitals",
    "- Reading medical research papers and journals",
    "- Attending medical/scientific seminars or webinars",
    "",
    "**3. Develop Leadership Skills**",
    "DMS students are expected to become leaders in academic medicine. Build your leadership portfolio:",
    "- Student council or prefect roles",
    "- Leading school clubs or societies (especially science/medical related)",
    "- Organising community service projects",
    "- Captaincy in sports or academic teams",
    "",
    "**4. Excel in the Interview**",
    "The interview assesses whether you have the qualities of a future medical academic:",
    "- Articulate WHY you want to pursue academic medicine (not just 'I want to be a doctor')",
    "- Discuss a medical research topic you're passionate about",
    "- Show critical thinking by analysing a healthcare issue",
    "- Demonstrate empathy and communication skills",
    "- Ask intelligent questions about the DMS programme",
    "",
    "**5. Build a Strong Academic Profile**",
    "- Achieve top grades in ALL subjects, especially Biology, Chemistry, and English",
    "- Consider taking M1/M2 to strengthen your quantitative skills for research",
    "- Participate in academic competitions (Biology Olympiad, Chemistry Olympiad)",
    "- Maintain a strong overall academic record",
    "",
    "**6. Understand the DMS Commitment**",
    "DMS is not just about getting into MBBS — it's a commitment to academic medicine:",
    "- You will complete an MRes[Med] during your Enrichment Year",
    "- You are expected to pursue a PhD after internship (with Faculty support)",
    "- Your career path will likely involve research, teaching, and clinical practice",
    "- Make sure this aligns with your long-term goals",
    "",
    "**7. Apply to Both JS6456 and JS6626**",
    "- You can place both JS6456 (MBBS) and JS6626 (DMS) in your JUPAS choices",
    "- If not selected for DMS, you may still be admitted to standard MBBS",
    "- Strategically place DMS higher if it's your top choice",
    "",
    "**8. Prepare for the Academic Pathway**",
    "- Read about current medical research at HKU (cancer, infectious diseases, neuroscience)",
    "- Familiarise yourself with the MRes[Med] and PhD pathway",
    "- Understand what academic medicine entails (research + teaching + clinical work)",
    "- Speak to current DMS students or academic doctors if possible",
    "",
    "**9. Have a Backup Plan**",
    "- DMS is extremely competitive. Even exceptional students may not be selected",
    "- Standard MBBS (JS6456) is an excellent alternative with the same core training",
    "- Other medical programmes (CUHK Medicine, Chinese Medicine) are viable options",
    "- Biomedical Sciences can be a stepping stone to graduate medicine"
]

zh_admission = [
    "**JUPAS 編號：** JS6626 | **大學：** 香港大學",
    "**課程：** 內外全科醫學士 - 傑出醫科學人 (Distinguished MedScholar) | **學院：** 李嘉誠醫學院",
    "**修讀年期：** 6年（全日制）| **首年學額：** 300人（與 JS6456 內外全科醫學士共用學額）",
    "**資助類別：** 教資會資助",
    "",
    "**最低 DSE 入學要求：**",
    "- 中國語文：第3級",
    "- 英國語文：第4級",
    "- 數學（必修部分）：第2級",
    "- 公民與社會發展：達標",
    "- 兩科選修科目：均達第3級，其中一科必須為生物或化學（或 M1/M2 達第3級 + 生物／化學）",
    "",
    "**額外要求：** 須具備良好的粵語工作能力，以應對臨床培訓。",
    "",
    "**計分方法：** 最佳6科 DSE 成績（只計算甲類科目及M1/M2）",
    "",
    "**面試安排：** 設有選擇性面試。包括個人面試（英語及中文）及小組面試（英語）。",
    "",
    "**注意：** 此課程與 JS6456（內外全科醫學士）共用300個學額。傑出醫科學人軌道的錄取基於學業卓越表現及面試成績。",
    "",
    "**2025年入學分數（與 JS6456 共用，已獲錄取學生）：**",
    "- 中位數：44分",
    "- 上四分位數：47分",
    "- 下四分位數：42分"
]

zh_curriculum = [
    "傑出醫科學人（DMS）軌道沿用與 JS6456 相同的 **6年內外全科醫學士課程**，並提供額外的學術培育機會，旨在培養學術卓越的醫學人才。",
    "",
    "**核心 MBBS 課程（與 JS6456 相同）：**",
    "- 第一至二年：臨床前培訓（解剖學、生理學、生物化學、病理學、藥理學）",
    "- 第三至五年：臨床輪換（內科、外科、兒科、婦產科、精神科等）",
    "- 第六年：臨床選修、溫習及執業資格試準備",
    "",
    "**傑出醫科學人獨有特色：**",
    "",
    "**1. 增潤年（第三年）**",
    "- DMS 學生於增潤年修讀醫學研究碩士（MRes[Med]）",
    "- 在教職員指導下接受研究培訓",
    "- 可選擇於增潤年修讀其他學士或碩士課程",
    "- 在標準6年學制內額外取得一個學位",
    "",
    "**2. 精英導師計劃**",
    "- 保證獲配精英導師，可從學院或大學內自選導師",
    "- 由頂尖醫學研究者及臨床醫生提供一對一指導",
    "- 職業規劃及學術發展支援",
    "",
    "**3. 學術工作坊及社區項目**",
    "- 一系列學術工作坊，培養研究及批判思維技巧",
    "- 社區項目培養同理心及社會責任感",
    "- 參與前沿醫學研究的機會",
    "",
    "**4. 保證宿位**",
    "- 保證獲配學生宿舍宿位",
    "- 宿舍費用可能獲醫學院財政支援",
    "",
    "**5. 博士課程支援**",
    "- 完成內外全科醫學士、醫學研究碩士及一年實習後，獲學院財政支援於知名大學修讀博士課程",
    "- 完成博士後有機會加入學院成為臨床學者",
    "",
    "**教學醫院：**",
    "- 瑪麗醫院（主要教學醫院）",
    "- 其他港大附屬醫院及診所"
]

zh_career = [
    "傑出醫科學人畢業生與標準內外全科醫學士畢業生擁有相同的專業出路，並享有額外的學術及研究機會。",
    "",
    "**專業註冊：**",
    "- 符合資格參加香港醫務委員會執業資格試",
    "- 通過後可於香港註冊成為醫生",
    "",
    "**就業出路：**",
    "1. **臨床診療** — 醫院管理局、私家執業或專科培訓",
    "2. **學術醫學** — 加入港大或其他大學成為臨床學者（獲博士課程支援）",
    "3. **醫學研究** — 領導研究項目，具備 MRes[Med] 及博士培訓",
    "4. **公共衛生及政策** — 政府衛生部門、世衛、非政府組織",
    "5. **醫療管理** — 醫院管理、醫療政策",
    "",
    "**DMS 獨有優勢：**",
    "- 增潤年透過 MRes[Med] 早期接觸研究",
    "- 獲學院財政支援於國際知名大學修讀博士",
    "- 獲頂尖教職員指導",
    "- 為學術醫學事業奠定穩固基礎",
    "",
    "**進修途徑：**",
    "- 醫學或相關領域博士課程（獲學院財政支援）",
    "- 香港或海外專科培訓",
    "- 公共衛生、醫學教育或醫療管理碩士課程"
]

zh_campus = [
    "**校園及設施：**",
    "- 設於港大本部校園（薄扶林）及沙宣道醫學院校園",
    "- 先進實驗室、解剖室及臨床模擬中心",
    "- 瑪麗醫院為主要教學醫院",
    "",
    "**學生生活（DMS 特色）：**",
    "- 保證獲配宿舍宿位，並可能獲費用資助",
    "- 與高成就醫科學生組成的緊密社群",
    "- 參與獨家學術工作坊及研討會",
    "- 研究興趣小組及期刊會",
    "- 專為 DMS 學生舉辦的社區服務項目",
    "",
    "**增潤年體驗：**",
    "- 全年專注於研究培訓（MRes[Med]）或另一學位",
    "- 與港大世界級研究者並肩工作",
    "- 本科階段發表研究論文的機會",
    "- 國際研究合作",
    "",
    "**導師指導：**",
    "- 自選學院教授或大學學者作為個人導師",
    "- 定期會面討論學術及職業發展",
    "- 與頂尖醫療專業人士建立人脈"
]

zh_competitiveness = [
    "**入學競爭力分析：**",
    "",
    "**競爭程度：** 極高 — 與 JS6456（內外全科醫學士）共用300個學額",
    "",
    "**重點：**",
    "- 傑出醫科學人軌道專為學業最卓越的內外全科醫學士申請者而設",
    "- 入學要求及計分方法與 JS6456（內外全科醫學士）相同",
    "- DMS 錄取基於卓越的 DSE 成績及出色的面試表現",
    "- 申請者須展示強大的學術研究及領導潛質",
    "",
    "**入學分數（與 JS6456 共用，2025年）：**",
    "- 中位數：44分（最佳6科）",
    "- 上四分位數：47分",
    "- 下四分位數：42分",
    "",
    "**DMS 與標準 MBBS 比較：**",
    "- DMS 學生通常比標準 MBBS 入學者擁有更強的學術背景",
    "- DMS 軌道在已經競爭激烈的 MBBS 池中進一步篩選",
    "- 並非所有 MBBS 申請者都獲考慮 DMS — 按成績邀請",
    "",
    "**成功入讀的關鍵因素：**",
    "1. **卓越的 DSE 成績** — 目標最佳6科達45分或以上以具 DMS 競爭力",
    "2. **出色的面試表現** — 展示研究興趣、領導潛質及學術好奇心",
    "3. **強大的 SLP/OEA** — 研究經驗、學術比賽、領導角色的證明",
    "4. **清晰的學術事業願景** — 闡述為何希望投身學術醫學",
    "5. **Band A 放置** — 與標準 MBBS 相同，必須放 Band A"
]

zh_alumni = [
    "**關於傑出醫科學人課程：**",
    "",
    "傑出醫科學人軌道是港大醫學院的旗艦課程，旨在培育未來的醫學學術及研究領袖。課程結合嚴謹的內外全科醫學士臨床培訓與進階研究教育。",
    "",
    "**學院領導：**",
    "- 由亞洲頂尖醫學院之一的李嘉誠醫學院領導",
    "- 世界知名研究者及臨床醫生擔任導師",
    "- 可使用港大廣泛的國際研究網絡",
    "",
    "**研究卓越：**",
    "- 港大醫學院位列全球頂尖醫學院之一",
    "- 於癌症、傳染病、神經科學及公共衛生領域具領先研究",
    "- 沙宣道校園設有先進研究設施",
    "",
    "**知名特色：**",
    "- 香港首間醫學院（1887年成立）",
    "- 培育醫學領袖及學者的悠久傳統",
    "- 與全球頂尖醫療機構的廣泛合作"
]

zh_scholarships = [
    "**傑出醫科學人財政支援：**",
    "",
    "**宿舍支援：**",
    "- 保證獲配學生宿舍宿位",
    "- 宿舍費用可能獲醫學院財政支援",
    "",
    "**博士課程支援：**",
    "- 完成內外全科醫學士、醫學研究碩士及實習後，獲學院財政支援於知名大學修讀博士",
    "- 資助博士期間的學費及生活費",
    "",
    "**港大入學獎學金：**",
    "- **港大基金入學獎學金** — 頒予 DSE 成績卓越的 JUPAS 申請人",
    "- **港大傑出學生獎學金** — 頒予核心科目及選修科目均獲5**的學生",
    "",
    "**政府資助：**",
    "- 專上學生資助計劃（TSFS）— 經入息審查的助學金及貸款",
    "- 免入息審查貸款計劃（NLS）— 所有合資格學生均可申請的低息貸款",
    "",
    "**其他機會：**",
    "- 醫學研究碩士項目研究資助",
    "- 國際會議旅費資助",
    "- 海外交流獎學金"
]

zh_tips = [
    "**Ace Sir 港大傑出醫科學人攻略 — 9個實戰貼士：**",
    "",
    "**1. 目標高於標準內外全科醫學士**",
    "DMS 是內外全科醫學士的精英軌道。標準 MBBS 中位數為44分，DMS 學生通常成績更高。建議目標最佳6科達45分或以上。",
    "",
    "**2. 早期展示研究興趣**",
    "DMS 專為未來學術醫生而設。展示以下證明：",
    "- 參與科學研究比賽（如香港學生科學比賽、ISEF）",
    "- 於大學或醫院進行研究實習",
    "- 閱讀醫學研究論文及期刊",
    "- 參加醫學／科學研討會或網上講座",
    "",
    "**3. 培養領導才能**",
    "DMS 學生預期成為學術醫學的領袖。建立領導履歷：",
    "- 學生會或領袖生職位",
    "- 領導學會或社團（尤其科學／醫學相關）",
    "- 籌辦社區服務項目",
    "- 擔任運動隊或學術隊隊長",
    "",
    "**4. 出色面試表現**",
    "面試評估你是否具備未來醫學學者的素質：",
    "- 清楚闡述為何希望投身學術醫學（不只是「我想做醫生」）",
    "- 討論你熱衷的醫學研究課題",
    "- 透過分析醫療議題展示批判思維",
    "- 展示同理心及溝通技巧",
    "- 就 DMS 課程提出有見地的問題",
    "",
    "**5. 建立強大學術背景**",
    "- 所有科目均取得頂尖成績，尤其生物、化學及英文",
    "- 考慮修讀 M1/M2 以增強研究所需的量化技巧",
    "- 參與學術比賽（生物奧林匹克、化學奧林匹克）",
    "- 保持整體卓越的學術紀錄",
    "",
    "**6. 了解 DMS 承諾**",
    "DMS 不只是入讀內外全科醫學士 — 是對學術醫學的承諾：",
    "- 增潤年須完成醫學研究碩士",
    "- 實習後預期修讀博士（獲學院支援）",
    "- 事業路徑可能涉及研究、教學及臨床診療",
    "- 確保這符合你的長遠目標",
    "",
    "**7. 同時申請 JS6456 及 JS6626**",
    "- 可於 JUPAS 選擇同時放置 JS6456（內外全科醫學士）及 JS6626（傑出醫科學人）",
    "- 若未獲選 DMS，仍可能入讀標準內外全科醫學士",
    "- 若 DMS 為首選，策略性地將其放於較高位置",
    "",
    "**8. 為學術路徑做好準備**",
    "- 閱讀港大當前醫學研究（癌症、傳染病、神經科學）",
    "- 了解 MRes[Med] 及博士路徑",
    "- 理解學術醫學的內涵（研究 + 教學 + 臨床工作）",
    "- 如有可能，與現任 DMS 學生或學術醫生交流",
    "",
    "**9. 要有後備方案**",
    "- DMS 競爭極為激烈。即使成績卓越的學生也未必獲選",
    "- 標準內外全科醫學士（JS6456）是具相同核心培訓的優秀替代選擇",
    "- 其他醫學課程（中大醫學、中醫）亦是可行選擇",
    "- 生物醫學可作為進修醫學的踏腳石"
]

details = {
    "code": "JS6626",
    "university": "香港大學",
    "en": {
        "sections": {
            "admission": {"title": "Eligibility & Admission Criteria (DSE)", "content": en_admission},
            "curriculum": {"title": "Programme Structure & Curriculum", "content": en_curriculum},
            "career": {"title": "Career Pathways & Prospects", "content": en_career},
            "campus": {"title": "Campus Life & Student Experience", "content": en_campus},
            "competitiveness": {"title": "Admission Competitiveness Analysis", "content": en_competitiveness},
            "alumni": {"title": "Notable Alumni & Faculty", "content": en_alumni},
            "scholarships": {"title": "Scholarships & Financial Aid", "content": en_scholarships},
            "tips": {"title": "Ace Sir's HKU Distinguished MedScholar Strategy", "content": en_tips}
        }
    },
    "zh": {
        "sections": {
            "admission": {"title": "入學要求與計分詳情 (DSE)", "content": zh_admission},
            "curriculum": {"title": "課程結構與內容", "content": zh_curriculum},
            "career": {"title": "職業前景與出路", "content": zh_career},
            "campus": {"title": "校園生活與學生體驗", "content": zh_campus},
            "competitiveness": {"title": "入學競爭力分析", "content": zh_competitiveness},
            "alumni": {"title": "知名校友及教職員", "content": zh_alumni},
            "scholarships": {"title": "獎學金及經濟援助", "content": zh_scholarships},
            "tips": {"title": "Ace Sir 港大傑出醫科學人攻略", "content": zh_tips}
        }
    }
}

container.upsert_item({**programme, "id": f"prog_{programme['code']}", "pk": "programmes", "type": "programme"})
container.upsert_item({**details, "id": f"detail_{details['code']}", "pk": "details", "type": "programme_detail"})
print(f"[Seed] {programme['code']} - {programme['nameEn']} / {programme['nameZh']} - Done!")
