import os
from dotenv import load_dotenv
from azure.cosmos import CosmosClient

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
endpoint = os.getenv("AZURE_COSMOS_ENDPOINT")
key = os.getenv("AZURE_COSMOS_KEY")
client = CosmosClient(endpoint, credential=key)
db = client.get_database_client(os.getenv("AZURE_COSMOS_DATABASE", "aceit"))
container = db.get_container_client("jupas_programmes")

programme = {
    "code": "JS6602",
    "nameEn": "Bachelor of Science in Innovation and Technology",
    "nameZh": "創新及科技學學士",
    "name": "Bachelor of Science in Innovation and Technology",
    "university": "香港大學",
    "faculty": "理學院（創新學院）",
    "median": 58,
    "band_a": 55,
    "uq": 52,
    "category": "science"
}

en_admission = [
    "**JUPAS Code:** JS6602 | **University:** The University of Hong Kong (HKU)",
    "**Programme:** Bachelor of Science in Innovation and Technology (BSc(I&T)) | **Faculty:** Faculty of Science (School of Innovation / I-School)",
    "**Duration:** 4 years (full-time) | **First Year Intake:** 25 students",
    "**Funding:** UGC-funded",
    "",
    "**Minimum DSE Entry Requirements:**",
    "- Chinese Language: Level 3",
    "- English Language: Level 3",
    "- Mathematics (Compulsory Part): Level 4 (higher than standard)",
    "- Citizenship and Social Development: Attained",
    "- Two Elective Subjects: Level 3 in BOTH, with specific subject requirements:",
    "  - One elective must be from: Biology, Chemistry, Physics, Information and Communication Technology (ICT), Design and Applied Technology, Technology and Living (Food Science and Technology), or Technology and Living (Fashion, Clothing and Textiles)",
    "  - Or M1/M2 at Level 3 + one of the above elective subjects",
    "",
    "**Preferred (Not Required):** Level 3 or above in Mathematics Extended Module 1 or 2 (M1/M2).",
    "",
    "**Scoring Formula:** Best 4 subjects (Category A subjects and M1/M2 only)",
    "",
    "**Interview:** Yes — MANDATORY individual interview for ALL applicants. The interview evaluates:",
    "- Creativity and innovative thinking",
    "- Analytical ability",
    "- Initiative and leadership potential",
    "- Sociability and teamwork skills",
    "- Aptitude for working on innovation projects",
    "",
    "Candidates are encouraged to prepare a short presentation of past projects for the interview.",
    "",
    "**2025 Admission Statistics:**",
    "- Band A applicants: 85",
    "- Total applicants: 626",
    "- Offers made: 23 (100% from Band A)",
    "",
    "**Admissions Scores (2025 admitted students):**",
    "- Median: 58 points (Best 4 subjects)",
    "- Upper Quartile (UQ): 52 points",
    "- Lower Quartile (LQ): 55 points",
    "",
    "**Note:** Level 2 in Liberal Studies achieved in previous sitting(s) will be considered in lieu of Citizenship and Social Development. Combined Science and Integrated Science results from previous sittings will also be considered."
]

en_curriculum = [
    "The BSc(I&T) curriculum is a **4-year project-led programme** offered by the School of Innovation (I-School). The programme integrates theory with practical hands-on experiences across science, technology, design, and entrepreneurship.",
    "",
    "**Core Philosophy:**",
    "'Innovation is a process that can only be mastered through practice.' Students learn by solving practical, ill-defined real-world problems through four years of project experiences.",
    "",
    "**Curriculum Components:**",
    "",
    "**1. Project Workshops (Backbone of Curriculum)**",
    "- Students work in teams to address real-world challenges with innovation projects",
    "- Each workshop involves working with partners from different walks of life to co-develop solutions",
    "- Projects help students explore interests in science and technology to form their own Technology Focus",
    "",
    "**2. Foundation Courses**",
    "- Integrating elements from engineering, science, design, and business",
    "- Equip students with solid hands-on skills and knowledge base for innovation",
    "",
    "**3. Technology Focus**",
    "- Students develop depth in a science or technology area that fascinates them",
    "- Select courses from Engineering and Science faculties to build expertise",
    "- Academic mentor helps curate a tailored Technology Focus",
    "- Team members in project studios may include chemists, electrical engineers, ecologists, etc.",
    "",
    "**4. Co-op Experience (Year 3)**",
    "- Spend 6 to 8 months working full-time on an innovation project",
    "- Placement at a company, startup, research lab, or even your own startup",
    "- Immerse in a work environment to experience real-world challenges",
    "",
    "**5. Capstone Project (Year 4)**",
    "- Year-long project: find the need, form your team, develop your solution, and pitch your idea",
    "- Experience the process of starting your own venture",
    "- May turn into your first dream company upon graduation",
    "",
    "**6. Free Electives**",
    "- Select courses outside of I-School to diversify study at HKU",
    "",
    "**Courses by Year:**",
    "- **Year 1:** Human-centred Innovation, Physical Computing, Computational Problem Solving, Modelling the World 1 & 2, Sensing the World, Sciences and Technologies through Time",
    "- **Year 2:** Innovations for the Future, Innovation and Entrepreneurship, Making Sciences, Forms and Materials",
    "- **Year 3:** Innovations for Social Impact, Co-op Experience",
    "- **Year 4:** Capstone Project, Free Electives",
    "",
    "**Teaching Approach:**",
    "- Problem-Based Learning (PBL) — no two problems are the same",
    "- Bespoke learning — pick up new skills and technologies as needed for each project",
    "- Integrative courses provide theoretical and practical foundations"
]

en_career = [
    "BSc(I&T) graduates are prepared for diverse career paths that leverage their innovation mindset, technical skills, and entrepreneurial spirit.",
    "",
    "**Career Pathways:**",
    "",
    "**1. Entrepreneur**",
    "- Start your own company",
    "- Join a startup company in early stages",
    "- Leverage capstone project as foundation for first venture",
    "",
    "**2. Intrapreneur**",
    "- Join large technology companies (e.g., Google, Apple, Microsoft, local tech giants)",
    "- Work in non-profits and forward-looking organisations",
    "- Lead innovation projects within established organisations",
    "- Drive digital transformation and new product development",
    "",
    "**3. Postgraduate Study**",
    "- Continue to address deeper scientific and technological challenges",
    "- Pursue MSc or PhD in engineering, science, or technology fields",
    "- Apply innovative and entrepreneurial mindset to research",
    "",
    "**4. Technology & Engineering Roles**",
    "- Software development and engineering",
    "- Product design and development",
    "- Data science and analytics",
    "- Hardware and physical computing",
    "- Research and development (R&D)",
    "",
    "**5. Consulting & Business**",
    "- Innovation consulting",
    "- Technology strategy",
    "- Business development in tech sectors",
    "- Project management",
    "",
    "**6. Social Innovation**",
    "- Work on innovations for social impact",
    "- Social enterprises addressing community needs",
    "- Non-profit technology initiatives"
]

en_campus = [
    "**Campus & Facilities:**",
    "- Based at HKU's Main Campus in Pok Fu Lam",
    "- School of Innovation (I-School) provides dedicated project studios and maker spaces",
    "- Access to HKU's extensive engineering and science laboratories",
    "- Collaborative spaces for team-based project work",
    "",
    "**Student Life:**",
    "- Small cohort of approximately 25 students fosters close community",
    "- Project studios bring together students with diverse technology focuses (chemistry, engineering, ecology, etc.)",
    "- Co-op experience provides 6–8 months of real-world work immersion",
    "- Opportunities to join promotional events: JUPAS Info Session, Summer Bootcamp",
    "- Cross-disciplinary collaboration with students from Engineering, Science, and Business faculties",
    "",
    "**Admission Events:**",
    "- JUPAS Information Sessions",
    "- Summer Bootcamps for prospective students",
    "- Structured admission interviews (May–June for JUPAS applicants)",
    "",
    "**Who is BSc(I&T) for?**",
    "Students who are:",
    "- Innovative and creative",
    "- Love to solve problems — both their own and other people's",
    "- Passionate about science, technology, engineering, and math (STEM)",
    "- Enjoy hands-on projects and building things",
    "- Not afraid of failure and willing to learn from mistakes"
]

en_competitiveness = [
    "**Admission Competitiveness Analysis:**",
    "",
    "**Competition Level:** HIGH — 3.7 Band A applicants per offer (85 Band A ÷ 23 offers)",
    "",
    "**Key Statistics (2025):**",
    "- Total applicants: 626",
    "- Band A applicants: 85",
    "- Offers: 23 (100% from Band A)",
    "- First Year Intake: 25 (some places reserved for non-JUPAS)",
    "",
    "**Score Analysis:**",
    "- Median: 58 points (Best 4 subjects)",
    "- This is equivalent to approximately 5555* or better in the best 4 subjects",
    "- The Best 4 formula means students can focus on their strongest subjects",
    "- Math Compulsory Part Level 4 is a higher bar than standard (most programmes require Level 2)",
    "",
    "**Critical Success Factors:**",
    "1. **Band A placement is ESSENTIAL** — 100% of offers go to Band A",
    "2. **Math Level 4** — Higher requirement than most programmes; filters out many applicants",
    "3. **Mandatory interview** — ALL applicants must attend. Interview performance is crucial and evaluates creativity, analytical ability, initiative, and sociability",
    "4. **STEM project portfolio** — Strong Student Learning Profile (SLP) with hands-on design, innovation, and/or STEM projects significantly strengthens application",
    "5. **OEA submission** — Awards/certificates from innovation/STEM competitions should be included",
    "6. **M1/M2 preferred** — Level 3+ in M1/M2 is preferred (though not required) and may strengthen application",
    "7. **Subject combination flexibility** — Accepts diverse STEM-related electives including ICT, Design and Applied Technology, and Technology and Living"
]

en_alumni = [
    "**About the School of Innovation (I-School):**",
    "",
    "The School of Innovation is a new initiative within HKU's Faculty of Science, designed to nurture the next generation of innovators and technology leaders. The I-School brings together expertise from across engineering, science, design, and business disciplines.",
    "",
    "**Programme Leadership:**",
    "- The programme is led by faculty with expertise in innovation, design thinking, engineering, and entrepreneurship",
    "- Academic mentors guide students in curating their personalised Technology Focus",
    "",
    "**Unique Features:**",
    "- Project-led curriculum — the first of its kind at HKU",
    "- Co-op experience integrated into the degree",
    "- Capstone project designed as a venture-building experience",
    "- Cross-disciplinary collaboration across faculties",
    "",
    "**HKU Science Faculty:**",
    "- Ranked among the world's top science faculties",
    "- Strong research excellence across physical sciences, life sciences, and earth sciences",
    "- Extensive international collaborations and exchange opportunities"
]

en_scholarships = [
    "**HKU Entrance Scholarships:**",
    "- **HKU Foundation Entrance Scholarship** — For outstanding JUPAS applicants with exceptional DSE results",
    "- **HKU Outstanding Students Scholarship** — For students with all 5** in core and elective subjects",
    "",
    "**Faculty-Specific Scholarships:**",
    "- Faculty of Science scholarships for academic excellence",
    "- Research scholarships for students participating in innovation projects",
    "",
    "**Government Financial Aid:**",
    "- Tertiary Student Finance Scheme (TSFS) — Means-tested grant and loan",
    "- Non-means-tested Loan Scheme (NLS) — Low-interest loan for all eligible students",
    "",
    "**Other Opportunities:**",
    "- Innovation and entrepreneurship competition prizes",
    "- Industry-sponsored scholarships for co-op placements",
    "- Funding for capstone project development"
]

en_tips = [
    "**Ace Sir's HKU BSc(I&T) Strategy — 9 Actionable Tips:**",
    "",
    "**1. Band A is Mandatory**",
    "100% of offers go to Band A applicants. If BSc(I&T) is your goal, you MUST place JS6602 in Band A.",
    "",
    "**2. Math Compulsory Part Level 4 is Your First Filter**",
    "Most programmes require Math Level 2. BSc(I&T) requires Level 4 — this immediately filters out many applicants. Ensure your math fundamentals are strong. Practice past papers extensively and aim for Level 5 or above to be safe.",
    "",
    "**3. Build a STEM Project Portfolio**",
    "The interview focuses heavily on your hands-on experience. Start building projects NOW:",
    "- Arduino/Raspberry Pi projects (Physical Computing)",
    "- Mobile app or web development projects",
    "- Design projects (CAD, 3D printing)",
    "- Science fair or innovation competition entries",
    "- Any project that shows problem-solving and creativity",
    "Document everything with photos, videos, and code repositories (GitHub).",
    "",
    "**4. Prepare for the Mandatory Interview**",
    "The interview is NOT optional — every applicant must attend. Expect:",
    "- Hackathon-style challenges (solve a problem on the spot)",
    "- Presentation of past projects (bring prototypes, portfolios, demos)",
    "- Questions assessing creativity, analytical thinking, and teamwork",
    "- Scenarios testing how you handle failure and iterate",
    "Practice presenting your projects clearly in 2–3 minutes. Be ready to explain your design decisions, challenges faced, and how you improved.",
    "",
    "**5. Take M1/M2 if Possible**",
    "M1/M2 at Level 3+ is preferred (though not required). It strengthens your application and prepares you for the computational and modelling aspects of the programme. If you're considering BSc(I&T), M1/M2 is highly recommended.",
    "",
    "**6. Choose the Right Elective Combination**",
    "You need one STEM-related elective from: Biology, Chemistry, Physics, ICT, Design and Applied Technology, or Technology and Living. ICT or Design and Applied Technology are most aligned with the innovation focus. Physics is also excellent for understanding sensing and computing. Choose based on your interests and strengths.",
    "",
    "**7. Submit a Strong SLP and OEA**",
    "- SLP: Highlight hands-on design, innovation, and STEM project experiences",
    "- Include a portfolio of designs or evidence of achievements",
    "- OEA: Include awards/certificates from innovation/STEM competitions",
    "- Join I-School promotional events (Info Session, Summer Bootcamp) and mention attendance",
    "",
    "**8. Embrace the Mindset**",
    "BSc(I&T) is NOT a traditional science degree. You will:",
    "- Work on open-ended problems without clear answers",
    "- Fail frequently and learn to iterate",
    "- Collaborate with diverse teammates from different backgrounds",
    "- Present and pitch your ideas regularly",
    "- Spend 6–8 months on co-op away from campus",
    "If you prefer structured, exam-heavy learning, this may not be the right fit.",
    "",
    "**9. Have a Backup Plan**",
    "With only 23 JUPAS offers and 85 Band A applicants, admission is competitive. Consider:",
    "- HKU BSc (JS6901) — broader science programme with more places",
    "- HKUST BEng/BSc in Engineering/Science — similar STEM focus",
    "- CUHK Engineering or Science programmes",
    "- CityU/Speed innovation-related programmes",
    "- Remember: BSc(I&T) is a new and unique programme — there are few direct alternatives"
]

zh_admission = [
    "**JUPAS 編號：** JS6602 | **大學：** 香港大學",
    "**課程：** 創新及科技學學士 (BSc(I&T)) | **學院：** 理學院（創新學院 / I-School）",
    "**修讀年期：** 4年（全日制）| **首年學額：** 25人",
    "**資助類別：** 教資會資助",
    "",
    "**最低 DSE 入學要求：**",
    "- 中國語文：第3級",
    "- 英國語文：第3級",
    "- 數學（必修部分）：第4級（高於一般要求）",
    "- 公民與社會發展：達標",
    "- 兩科選修科目：均達第3級，須符合特定科目要求：",
    "  - 一科選修須為：生物、化學、物理、資訊及通訊科技、設計與應用科技、科技與生活（食品科學與科技）或科技與生活（時裝、成衣與紡織）",
    "  - 或 M1/M2 達第3級 + 上述其中一科選修",
    "",
    "**優先考慮（非必須）：** 數學延伸部分（M1/M2）達第3級或以上。",
    "",
    "**計分方法：** 最佳4科 DSE 成績（只計算甲類科目及M1/M2）",
    "",
    "**面試安排：** 設有**強制性**個人面試，所有申請者均須參加。面試評估：",
    "- 創意及創新思維",
    "- 分析能力",
    "- 主動性及領導潛質",
    "- 社交能力及團隊合作技巧",
    "- 從事創新項目的潛質",
    "",
    "申請者獲鼓勵準備過往項目的簡短介紹於面試中展示。",
    "",
    "**2025年入學統計：**",
    "- Band A 申請人數：85人",
    "- 總申請人數：626人",
    "- 錄取名額：23人（100%來自 Band A）",
    "",
    "**2025年入學分數（已獲錄取學生）：**",
    "- 中位數：58分（最佳4科）",
    "- 上四分位數：52分",
    "- 下四分位數：55分",
    "",
    "**注意：** 以往考試中達第2級的通識教育科可代替公民與社會發展科。以往考試的組合科學及綜合科學成績亦獲考慮。"
]

zh_curriculum = [
    "BSc(I&T) 課程是由創新學院（I-School）開辦的 **4年項目導向課程**，將理論與橫跨科學、科技、設計及創業的實踐經驗結合。",
    "",
    "**核心哲學：**",
    "「創新是一個只能透過實踐掌握的過程。」學生透過四年項目經驗，解決實際、定義模糊的現實問題。",
    "",
    "**課程組成：**",
    "",
    "**1. 項目工作坊（課程骨幹）**",
    "- 學生以小組形式解決現實世界的創新挑戰",
    "- 與各行各業的夥伴合作共同開發解決方案",
    "- 項目幫助學生探索科學及科技興趣，形成個人科技專長",
    "",
    "**2. 基礎課程**",
    "- 整合工程、科學、設計及商業元素",
    "- 為創新旅程建立穩固的實踐技能及知識基礎",
    "",
    "**3. 科技專長**",
    "- 學生於感興趣的科學或科技領域建立深度",
    "- 從工程學院及理學院選課以建立專業知識",
    "- 學術導師協助策劃個人化的科技專長",
    "- 項目工作室的隊友可能包括化學家、電機工程師、生態學家等",
    "",
    "**4. 協作學習體驗（第三年）**",
    "- 全職工作6至8個月，從事創新項目",
    "- 於企業、初創公司、研究實驗室或自己的初創公司實習",
    "- 沉浸於工作環境，體驗現實挑戰",
    "",
    "**5. 畢業專題項目（第四年）**",
    "- 為期一年的項目：發現需求、組建團隊、開發方案、推銷構思",
    "- 體驗創業的完整過程",
    "- 可能成為畢業後的第一間夢想公司",
    "",
    "**6. 自由選修課程**",
    "- 選修創新學院以外的課程，豐富港大學習體驗",
    "",
    "**各年課程：**",
    "- **第一年：** 以人為本的創新、物理運算、運算解難、模擬世界（一）及（二）、感知世界、科學與科技縱覽",
    "- **第二年：** 未來創新、創新與創業、製造科學、形態與物料",
    "- **第三年：** 社會影響創新、協作學習體驗",
    "- **第四年：** 畢業專題項目、自由選修",
    "",
    "**教學模式：**",
    "- 問題導向學習（PBL）— 沒有兩個問題是相同的",
    "- 度身訂造學習 — 按每個項目的需要學習新技能及科技",
    "- 整合課程提供理論及實踐基礎"
]

zh_career = [
    "BSc(I&T) 畢業生具備創新思維、技術技能及創業精神，適合多元化的職業路徑。",
    "",
    "**就業出路：**",
    "",
    "**1. 創業家**",
    "- 創立自己的公司",
    "- 加入初創企業",
    "- 以畢業專題項目為基礎開展第一項事業",
    "",
    "**2. 企業內部創業家**",
    "- 加入大型科技公司（如 Google、Apple、微軟或本地科技巨頭）",
    "- 於非牟利機構及前瞻性機構工作",
    "- 於現有機構內領導創新項目",
    "- 推動數碼轉型及新產品開發",
    "",
    "**3. 進修研究**",
    "- 繼續探討更深層次的科學及科技挑戰",
    "- 修讀工程、科學或科技領域的碩士或博士課程",
    "- 將創新及創業思維應用於研究",
    "",
    "**4. 科技及工程職位**",
    "- 軟件開發及工程",
    "- 產品設計及開發",
    "- 數據科學及分析",
    "- 硬件及物理運算",
    "- 研究及開發（R&D）",
    "",
    "**5. 顧問及商業**",
    "- 創新顧問",
    "- 科技策略規劃",
    "- 科技領域業務發展",
    "- 項目管理",
    "",
    "**6. 社會創新**",
    "- 從事社會影響創新項目",
    "- 社會企業解決社區需求",
    "- 非牟利科技計劃"
]

zh_campus = [
    "**校園及設施：**",
    "- 課程設於港大本部校園（薄扶林）",
    "- 創新學院（I-School）提供專屬項目工作室及創客空間",
    "- 可使用港大廣泛的工程及科學實驗室",
    "- 團隊項目協作空間",
    "",
    "**學生生活：**",
    "- 每年約25人的小規模收生，建立緊密社群",
    "- 項目工作室匯聚不同科技專長的學生（化學、工程、生態學等）",
    "- 協作學習體驗提供6–8個月真實工作沉浸",
    "- 參加宣傳活動：JUPAS 資訊日、暑期訓練營",
    "- 與工程學院、理學院及商學院學生的跨學科合作",
    "",
    "**入學活動：**",
    "- JUPAS 資訊日",
    "- 準學生暑期訓練營",
    "- 結構化入學面試（JUPAS 申請者為5月至6月）",
    "",
    "**BSc(I&T) 適合甚麼學生？**",
    "適合具備以下特質的學生：",
    "- 具創意及創新精神",
    "- 熱愛解難 — 無論是自己的還是別人的問題",
    "- 熱愛科學、科技、工程及數學（STEM）",
    "- 喜歡動手做項目及製作東西",
    "- 不怕失敗，願意從錯誤中學習"
]

zh_competitiveness = [
    "**入學競爭力分析：**",
    "",
    "**競爭程度：** 高 — 每個學額有3.7位 Band A 申請者（85人 ÷ 23個名額）",
    "",
    "**主要數據（2025年）：**",
    "- 總申請人數：626人",
    "- Band A 申請人數：85人",
    "- 錄取名額：23人（100%來自 Band A）",
    "- 首年學額：25人（部分保留予非 JUPAS 申請者）",
    "",
    "**分數分析：**",
    "- 中位數：58分（最佳4科）",
    "- 約相等於最佳4科達5555*或更佳成績",
    "- 最佳4科計分法讓學生可集中發揮最強科目",
    "- 數學必修部分第4級要求高於一般課程（大部分課程只要求第2級）",
    "",
    "**成功入讀的關鍵因素：**",
    "1. **必須放 Band A** — 100%錄取來自 Band A",
    "2. **數學必修部分第4級** — 高於一般課程要求，已篩走不少申請者",
    "3. **強制性面試** — 所有申請者均須參加。面試表現至關重要，評估創意、分析能力、主動性及社交能力",
    "4. **STEM 項目作品集** — 包含動手設計、創新及／或 STEM 項目經驗的強大學生學習概覽可大幅增強申請",
    "5. **OEA 提交** — 應包括創新／STEM 比賽的獎項／證書",
    "6. **M1/M2 優先考慮** — M1/M2 達第3級或以上為優先考慮（非必須），可增強申請",
    "7. **選修科組合靈活** — 接受資訊及通訊科技、設計與應用科技、科技與生活等多元化 STEM 相關選修科"
]

zh_alumni = [
    "**關於創新學院（I-School）：**",
    "",
    "創新學院是港大理學院的新舉措，旨在培養新一代創新者及科技領袖。I-School 匯聚工程、科學、設計及商業領域的專業知識。",
    "",
    "**課程領導：**",
    "- 課程由具創新、設計思維、工程及創業專長的教職員領導",
    "- 學術導師指導學生策劃個人化的科技專長",
    "",
    "**獨特之處：**",
    "- 項目導向課程 — 港大首創",
    "- 協作學習體驗融入學位課程",
    "- 畢業專題項目設計為創業體驗",
    "- 跨學院合作",
    "",
    "**港大理學院：**",
    "- 位列全球頂尖理學院之一",
    "- 於物理科學、生命科學及地球科學領域具卓越研究實力",
    "- 廣泛的國際合作及交流機會"
]

zh_scholarships = [
    "**港大入學獎學金：**",
    "- **港大基金入學獎學金** — 頒予 DSE 成績卓越的 JUPAS 申請人",
    "- **港大傑出學生獎學金** — 頒予核心科目及選修科目均獲5**的學生",
    "",
    "**學院獎學金：**",
    "- 理學院學業成績優異獎學金",
    "- 參與創新項目的研究獎學金",
    "",
    "**政府資助：**",
    "- 專上學生資助計劃（TSFS）— 經入息審查的助學金及貸款",
    "- 免入息審查貸款計劃（NLS）— 所有合資格學生均可申請的低息貸款",
    "",
    "**其他機會：**",
    "- 創新及創業比賽獎金",
    "- 協作學習實習的業界贊助獎學金",
    "- 畢業專題項目開發資助"
]

zh_tips = [
    "**Ace Sir 港大創新及科技學學士攻略 — 9個實戰貼士：**",
    "",
    "**1. 必須放 Band A**",
    "100%錄取來自 Band A 申請者。若 BSc(I&T) 是你的目標，必須將 JS6602 放在 Band A。",
    "",
    "**2. 數學必修部分第4級是第一道關卡**",
    "大部分課程要求數學第2級，BSc(I&T) 要求第4級 — 這已篩走不少申請者。確保數學基礎穩固，大量練習歷屆試題，目標為第5級或以上以穩妥入讀。",
    "",
    "**3. 建立 STEM 項目作品集**",
    "面試高度重視你的實踐經驗。現在就開始建立項目：",
    "- Arduino／Raspberry Pi 項目（物理運算）",
    "- 手機應用程式或網頁開發項目",
    "- 設計項目（CAD、3D打印）",
    "- 科學展覽或創新比賽參賽作品",
    "- 任何展示解難能力及創意的項目",
    "以照片、影片及程式碼庫（GitHub）記錄所有項目。",
    "",
    "**4. 準備強制性面試**",
    "面試不是選擇性的 — 每位申請者均須參加。預計會有：",
    "- 黑客馬拉松式挑戰（即場解決問題）",
    "- 過往項目介紹（帶備原型、作品集、示範）",
    "- 評估創意、分析思維及團隊合作的提問",
    "- 測試如何面對失敗及迭代的場景",
    "練習以2–3分鐘清楚介紹你的項目。準備好解釋設計決定、面對的挑戰及如何改進。",
    "",
    "**5. 盡量修讀 M1/M2**",
    "M1/M2 達第3級或以上為優先考慮（非必須）。這可增強申請並為課程的運算及模擬方面做好準備。若你考慮 BSc(I&T)，強烈建議修讀 M1/M2。",
    "",
    "**6. 選擇正確的選修科組合**",
    "你需要一科 STEM 相關選修科：生物、化學、物理、資訊及通訊科技、設計與應用科技或科技與生活。資訊及通訊科技或設計與應用科技最符合創新方向。物理對於理解感測及運算亦非常出色。按興趣及強項選擇。",
    "",
    "**7. 提交強大的 SLP 及 OEA**",
    "- SLP：強調動手設計、創新及 STEM 項目經驗",
    "- 包括設計作品集或成就證明",
    "- OEA：包括創新／STEM 比賽的獎項／證書",
    "- 參加 I-School 宣傳活動（資訊日、暑期訓練營）並於申請中提及",
    "",
    "**8. 擁抱這種思維模式**",
    "BSc(I&T) 不是傳統的科學學位。你將會：",
    "- 處理沒有明確答案的開放式問題",
    "- 經常失敗並學會迭代",
    "- 與來自不同背景的不同隊友合作",
    "- 經常介紹及推銷你的想法",
    "- 離校6至8個月進行協作學習",
    "若你偏好結構化、考試為重的學習模式，這可能不適合你。",
    "",
    "**9. 要有後備方案**",
    "只有約23個 JUPAS 學額，85位 Band A 申請者，入學競爭激烈。建議考慮：",
    "- 港大理學士（JS6901）— 更廣泛的科學課程，學額較多",
    "- 科大工程學／理學士 — 類似的 STEM 重點",
    "- 中大工程或科學課程",
    "- 城大／都大創新相關課程",
    "- 記住：BSc(I&T) 是新穎獨特的課程 — 直接替代選擇不多"
]

details = {
    "code": "JS6602",
    "university": "香港大學",
    "en": {
        "sections": {
            "admission": {"title": "Eligibility & Admission Criteria (DSE)", "content": en_admission},
            "curriculum": {"title": "Programme Structure & Curriculum", "content": en_curriculum},
            "career": {"title": "Career Pathways & Prospects", "content": en_career},
            "campus": {"title": "Campus Life & Student Experience", "content": en_campus},
            "competitiveness": {"title": "Admission Competitiveness Analysis", "content": en_competitiveness},
            "alumni": {"title": "Notable Alumni & Faculty", "content": en_alumni},
            "scholarships": {"title": "Scholarships & Financial Aid", "content": en_scholarships},
            "tips": {"title": "Ace Sir's HKU BSc(I&T) Strategy", "content": en_tips}
        }
    },
    "zh": {
        "sections": {
            "admission": {"title": "入學要求與計分詳情 (DSE)", "content": zh_admission},
            "curriculum": {"title": "課程結構與內容", "content": zh_curriculum},
            "career": {"title": "職業前景與出路", "content": zh_career},
            "campus": {"title": "校園生活與學生體驗", "content": zh_campus},
            "competitiveness": {"title": "入學競爭力分析", "content": zh_competitiveness},
            "alumni": {"title": "知名校友及教職員", "content": zh_alumni},
            "scholarships": {"title": "獎學金及經濟援助", "content": zh_scholarships},
            "tips": {"title": "Ace Sir 港大創新及科技學學士攻略", "content": zh_tips}
        }
    }
}

container.upsert_item({**programme, "id": f"prog_{programme['code']}", "pk": "programmes", "type": "programme"})
container.upsert_item({**details, "id": f"detail_{details['code']}", "pk": "details", "type": "programme_detail"})
print(f"[Seed] {programme['code']} - {programme['nameEn']} / {programme['nameZh']} - Done!")
