import os
from dotenv import load_dotenv
from azure.cosmos import CosmosClient

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
endpoint = os.getenv("AZURE_COSMOS_ENDPOINT")
key = os.getenv("AZURE_COSMOS_KEY")
client = CosmosClient(endpoint, credential=key)
db = client.get_database_client(os.getenv("AZURE_COSMOS_DATABASE", "aceit"))
container = db.get_container_client("jupas_programmes")

programme = {
    "code": "JS6494",
    "nameEn": "Bachelor of Pharmacy",
    "nameZh": "藥劑學學士",
    "name": "Bachelor of Pharmacy",
    "university": "香港大學",
    "faculty": "醫學院",
    "median": 41,
    "band_a": 39,
    "uq": 38,
    "category": "medicine"
}

en_admission = [
    "**JUPAS Code:** JS6494 | **University:** The University of Hong Kong (HKU)",
    "**Programme:** Bachelor of Pharmacy (BPharm) | **Faculty:** Faculty of Medicine (Department of Pharmacology and Pharmacy)",
    "**Duration:** 4 years (full-time) | **First Year Intake:** 35 students",
    "**Funding:** UGC-funded",
    "",
    "**Minimum DSE Entry Requirements:**",
    "- Chinese Language: Level 3",
    "- English Language: Level 4 (higher than standard university requirement)",
    "- Mathematics (Compulsory Part): Level 2",
    "- Citizenship and Social Development: Attained",
    "- Two Elective Subjects: Level 3 in BOTH, one of which MUST be Chemistry",
    "- Mathematics Extended Part (M1/M2) can substitute as a full elective subject",
    "",
    "**Additional Requirements:** A good working knowledge of Cantonese is required.",
    "",
    "**Scoring Formula:** Best 6 HKDSE subjects (Category A subjects and M1/M2 only)",
    "",
    "**Interview:** Yes — conducted on a selective basis. Interview performance, number of Level 5**/5*/5 grades, and student learning profile are all considered.",
    "",
    "**2025 Admission Statistics:**",
    "- Band A applicants: 123",
    "- Total applicants: 1,297",
    "- Offers made: 27 (100% from Band A)",
    "",
    "**Admissions Scores (2025 admitted students):**",
    "- Median: 41 points",
    "- Upper Quartile (UQ): 38 points",
    "- Lower Quartile (LQ): 39 points",
    "",
    "**Note on Repeaters:** Penalty will be imposed on subjects which were retaken. Latest results in the recent three years are considered."
]

en_curriculum = [
    "The BPharm curriculum is a comprehensive **4-year programme** comprising **258 credits**, including:",
    "",
    "**Credit Breakdown:**",
    "- Pharmacy core courses: 192 credits",
    "- Pharmacy electives: 12 credits",
    "- Common Core courses: 36 credits",
    "- Language courses: 18 credits",
    "",
    "**Year 1:** Essential Skills for Pharmacy Students, Integrated Course in Basic Sciences (Anatomy, Physiology & Biochemistry), Research Methods in Pharmacy Practice, Introduction to Pharmacy, Drug Discovery, Core University English, Common Core Courses",
    "",
    "**Year 2:** Pharmaceutical Chemistry, Dosage Form Design, Pharmacy in Body System Series (Cardiovascular & Renal, Gastrointestinal System, Drug Kinetics and Toxicities, Respiratory System), Pharmacy Practice: Introduction, Academic Communication for Pharmacy Students, Practical Chinese for Pharmacy Students, Common Core Courses",
    "",
    "**Year 3:** Advanced Drug Delivery, Pharmaceutical Analysis, Pharmacy Practice: Community Pharmacy, Pharmacy in Body System Series (Endocrinology, Central Nervous System, Musculoskeletal and Connective Tissue Disorders, Microbiology and Infectious Diseases, Oncology)",
    "",
    "**Year 4:** Research Methodology and Research Project, Pharmacy Practice: Pharmacy Law and Ethics, Industrial Drug Development, Biopharmaceutical Technology and Future Medicines, Pharmacotherapy of Special Populations, Enrichment Modules, Electives",
    "",
    "**Elective Courses:**",
    "- Molecular Medicine",
    "- Molecular Pharmacology",
    "- Big Data in Healthcare",
    "- Chinese Medicine for Pharmacy Students",
    "- Cardiopulmonary and Renal Systems (for MBBS articulation)",
    "",
    "**Teaching Pedagogies:**",
    "- **Problem-Based Learning (PBL)** — Applied throughout to encourage critical thinking and self-directed learning",
    "- **Pharmacy Experiential Education Programme (PEEP)** — Cumulative learning experience preparing students for advanced practice",
    "- **Patient Counselling and Communication Skills Training** — Step-by-step mastery of patient education in various settings",
    "- **Industrial Pharmacy Training** — Hands-on experience taught by industry experts",
    "- **Exposure to Chinese Medicine & Complementary/Alternative Medicine (CAM)** — Knowledge of herbal medicines, nutraceuticals, and healthcare products commonly used by local patients",
    "",
    "**Placement & Clerkship:**",
    "- Students rotate among hospital pharmacy, community pharmacy, and pharmaceutical industry (at least one week in each setting during final year)",
    "- Research project in specialised areas (pharmaceutics, pharmacology, pharmacy practice, clinical pharmacy) under academic supervision",
    "- Enrichment Modules offering tailored placement at academic institutions or non-profit community service organisations",
    "",
    "**Interprofessional Learning:**",
    "- Patient Care Project (PCP) involving collaboration with students from medicine, nursing, and Chinese medicine"
]

en_career = [
    "The programme is accredited by the **Pharmacy and Poisons Board of Hong Kong**. Graduates who complete the degree plus **one year of internship** are qualified to become **registered pharmacists** in Hong Kong.",
    "",
    "**Career Pathways:**",
    "",
    "**1. Community Pharmacy**",
    "- Community pharmacist at chain and independent pharmacies",
    "- Primary care and business management",
    "- Locum pharmacist",
    "- Veterinary pharmacist",
    "",
    "**2. Hospital Pharmacy**",
    "- Hospital Authority and private hospitals",
    "- Dispensing pharmacy and Intravenous Admixture Service (PIVAS)",
    "- Clinical / Specialist Pharmacist (e.g., Paediatrics, Oncology)",
    "- Radiopharmacy",
    "- Medical Information and Clinical Trial support",
    "- Drug Procurement",
    "",
    "**3. Pharmaceutical Industry**",
    "- Local manufacturers and multinational corporations",
    "- Manufacture and Supply, Quality Assurance (QA)",
    "- Drug Research and Development (R&D)",
    "- Regulatory Affairs, Business Development",
    "- Medical Information, Sales and Marketing",
    "- Pharmacovigilance, Clinical Trial management",
    "",
    "**4. Government & Public Health**",
    "- Department of Health / Drug Office",
    "- Policy Planning, Pharmacovigilance",
    "- Inspection, Drug Registration",
    "- Clinical Service, Public Health",
    "",
    "**5. Academia & Research**",
    "- Universities and higher education institutes",
    "- Pharmacy education (trainers or technicians)",
    "- Scientific research, health promotion, knowledge transfer",
    "- Further study (PhD, Medical or research degrees)",
    "",
    "**6. Other Roles**",
    "- Medical Writer / Editor",
    "- Non-profit organisations (healthcare project coordination, visiting pharmacist in elderly homes)",
    "",
    "**Further Studies:**",
    "- Master of Advanced Pharmacy (taught postgraduate)",
    "- MPhil/PhD in pharmacy-related research",
    "- Articulation to MBBS for selected graduates (via elective pathway)"
]

en_campus = [
    "**Campus & Facilities:**",
    "- The programme is based at HKU's Main Campus in Pok Fu Lam",
    "- State-of-the-art laboratories for pharmaceutical chemistry, dosage form design, and pharmaceutical analysis",
    "- Clinical simulation facilities for patient counselling training",
    "",
    "**Student Life:**",
    "- Cohort of approximately 35 students per year",
    "- Pharmacy Experiential Education Programme (PEEP) provides longitudinal exposure to practice settings",
    "- Opportunities to develop professionalism, ethics, problem-solving, teamwork, and commitment to lifelong learning",
    "- International exchange opportunities through Enrichment Modules",
    "- Interprofessional learning with medical, nursing, and Chinese medicine students",
    "",
    "**Placement Opportunities:**",
    "- Work experience in various pharmacy settings during term time",
    "- Rotation among hospital pharmacy, community pharmacy, and pharmaceutical industry",
    "- Research project supervision by academic staff in specialised areas",
    "- Placements at largest community pharmacy chain stores in Hong Kong",
    "",
    "**Student Testimonials:**",
    "'From offering professional advice for common illnesses at community pharmacy, to researching new treatments for life-threatening diseases, pharmacists impact people's lives in different aspects every day. This is a profession with huge diversity that I am honoured to be a part of.' — Ms Wynne Hui, BPharm 2015, Pharmacist in Drug Office, Department of Health",
    "",
    "'Using our specialised drug knowledge to optimise the medical treatment for patients is what makes our job as pharmacists meaningful.' — Ms Jody Chu, Senior Lecturer, Department of Pharmacology and Pharmacy"
]

en_competitiveness = [
    "**Admission Competitiveness Analysis:**",
    "",
    "**Competition Level:** VERY HIGH — 4.6 Band A applicants per offer (123 Band A ÷ 27 offers)",
    "",
    "**Key Statistics (2025):**",
    "- Total applicants: 1,297",
    "- Band A applicants: 123",
    "- Offers: 27 (100% from Band A)",
    "- First Year Intake: 35 (some places reserved for non-JUPAS)",
    "",
    "**Historical Trend:**",
    "- Offers have ranged from 27–32 in recent years",
    "- 100% of offers consistently go to Band A applicants",
    "- Total applicants have remained stable around 1,200–1,400",
    "",
    "**Score Analysis:**",
    "- Median: 41 points (Best 6 subjects)",
    "- This is equivalent to approximately 5*555555 or better across 6 subjects",
    "- The Best 6 formula rewards breadth — students need strength across ALL subjects, not just top 5",
    "- English Level 4 is a strict requirement (higher than most programmes' Level 3)",
    "",
    "**Critical Success Factors:**",
    "1. **Band A placement is ESSENTIAL** — No offers to Band B–E in recent history",
    "2. **Chemistry is MANDATORY** — Must achieve Level 3+ in Chemistry as one of two electives",
    "3. **English Level 4** — This is a higher bar than standard HKU requirements; weak English disqualifies regardless of other scores",
    "4. **Cantonese proficiency** — Required for community pharmacy practice in Hong Kong",
    "5. **Interview performance** — Selective interviews assess communication skills, motivation, and understanding of pharmacy profession",
    "6. **Student learning profile** — Relevant experiences (e.g., pharmacy volunteering, science research) strengthen applications",
    "7. **No penalty for Combined/Integrated Science** — Results from previous sittings are considered"
]

en_alumni = [
    "**Notable Faculty:**",
    "",
    "- **Professor Esther Chan** — Assistant Dean (Health Sciences Education), Professor, Department of Pharmacology and Pharmacy. Leading researcher in clinical pharmacy and pharmacotherapy.",
    "- **Ms Jody Chu** — Senior Lecturer, Department of Pharmacology and Pharmacy. Expert in clinical pharmacy practice and patient care.",
    "",
    "**Distinguished Alumni:**",
    "- **Ms Wynne Hui** (BPharm 2015) — Pharmacist in Drug Office, Department of Health, HKSAR. 'From offering professional advice for common illnesses at community pharmacy, to researching new treatments for life-threatening diseases, pharmacists impact people's lives in different aspects every day.'",
    "",
    "**Professional Recognition:**",
    "- Programme accredited by the Pharmacy and Poisons Board of Hong Kong",
    "- Graduates eligible for registered pharmacist status after one-year internship",
    "- HKU Faculty of Medicine ranked among top medical schools globally with 135+ years of history",
    "",
    "**Research Excellence:**",
    "- Department of Pharmacology and Pharmacy conducts cutting-edge research in drug discovery, pharmacotherapy, and clinical pharmacy",
    "- All Year 4 students complete a research project under academic supervision",
    "- Opportunities for research postgraduate study (MPhil/PhD)"
]

en_scholarships = [
    "**HKU Entrance Scholarships:**",
    "- **HKU Foundation Entrance Scholarship** — For outstanding JUPAS applicants with exceptional DSE results",
    "- **HKU Outstanding Students Scholarship** — For students with all 5** in core and elective subjects",
    "",
    "**Faculty-Specific Scholarships:**",
    "- Various scholarships and prizes offered by the Faculty of Medicine for academic excellence",
    "- Research scholarships for pharmacy students undertaking research projects",
    "",
    "**Government Financial Aid:**",
    "- Tertiary Student Finance Scheme (TSFS) — Means-tested grant and loan",
    "- Non-means-tested Loan Scheme (NLS) — Low-interest loan for all eligible students",
    "",
    "**Other Opportunities:**",
    "- Exchange scholarships for international placement through Enrichment Modules",
    "- Research grants for undergraduate research projects",
    "- Industry-sponsored scholarships from pharmaceutical companies"
]

en_tips = [
    "**Ace Sir's HKU BPharm Strategy — 9 Actionable Tips:**",
    "",
    "**1. Band A is Non-Negotiable**",
    "100% of offers go to Band A applicants. If pharmacy is your goal, you MUST place JS6494 in Band A. No exceptions.",
    "",
    "**2. Chemistry is Your Make-or-Break Subject**",
    "Chemistry at Level 3+ is MANDATORY. This is not negotiable. Aim for Level 5+ to be competitive. The programme is heavily chemistry-based (Pharmaceutical Chemistry, Dosage Form Design, Pharmaceutical Analysis). If you struggle with Chemistry, reconsider this programme.",
    "",
    "**3. English Level 4 is a Hard Gate**",
    "Unlike most HKU programmes requiring English Level 3, BPharm requires Level 4. This filters out many applicants. If your English is below Level 4, you are automatically disqualified regardless of other scores. Invest heavily in English preparation.",
    "",
    "**4. Target 41+ Points (Best 6)**",
    "The median is 41 points using Best 6 subjects. This means you need approximately 5*555555 or better across 6 subjects. Unlike Best 5 programmes, you cannot hide a weak 6th subject. Every subject matters. Aim for consistency across all subjects.",
    "",
    "**5. Build a Pharmacy-Focused Student Learning Profile**",
    "- Volunteer at community pharmacies (e.g., Watsons, Mannings, or independent pharmacies)",
    "- Shadow a pharmacist for a day to understand the profession",
    "- Read about drug discovery and pharmaceutical news (e.g., FDA approvals, new therapies)",
    "- Participate in chemistry or biology competitions",
    "- Demonstrate understanding of pharmacy's role in healthcare (NOT just 'dispensing medicine')",
    "",
    "**6. Prepare for the Selective Interview**",
    "Not all applicants are interviewed. If selected, expect:",
    "- 'Why pharmacy and not medicine/nursing?' (Have a genuine, specific answer)",
    "- Ethical scenarios (e.g., patient requests inappropriate medication)",
    "- Current healthcare issues (e.g., antibiotic resistance, opioid crisis)",
    "- Your understanding of pharmacy's evolving role (clinical pharmacy, not just dispensing)",
    "- Communication skills assessment (patient counselling scenario)",
    "",
    "**7. Cantonese Matters**",
    "A good working knowledge of Cantonese is required. Most patients in Hong Kong community pharmacies speak Cantonese. If you are not fluent in Cantonese, consider whether you can effectively counsel patients. This is a practical requirement, not just a formality.",
    "",
    "**8. Understand the 4-Year + 1-Year Internship Pathway**",
    "The degree is 4 years, but you need an additional 1-year internship to become a registered pharmacist. This means:",
    "- 5 years total before full registration",
    "- Internship placements are competitive (Hospital Authority, private hospitals, community chains)",
    "- Starting salary for registered pharmacists is attractive (~$50,000–60,000/month)",
    "- Career progression to specialist pharmacist roles is possible",
    "",
    "**9. Have a Backup Plan**",
    "With only ~27 JUPAS places and 123 Band A applicants, competition is intense. Consider:",
    "- CUHK Pharmacy (if available)",
    "- Biomedical Sciences or Biochemistry as related alternatives",
    "- Chemistry with interest in pharmaceutical applications",
    "- Overseas pharmacy schools (UK, Australia) if you have the resources",
    "- Remember: BPharm graduates can also pursue research, industry, or academia — not just community/hospital pharmacy"
]

zh_admission = [
    "**JUPAS 編號：** JS6494 | **大學：** 香港大學",
    "**課程：** 藥劑學學士 (BPharm) | **學院：** 醫學院（藥理學及藥學系）",
    "**修讀年期：** 4年（全日制）| **首年學額：** 35人",
    "**資助類別：** 教資會資助",
    "",
    "**最低 DSE 入學要求：**",
    "- 中國語文：第3級",
    "- 英國語文：第4級（高於一般大學要求的第3級）",
    "- 數學（必修部分）：第2級",
    "- 公民與社會發展：達標",
    "- 兩科選修科目：均達第3級，其中一科**必須**為化學",
    "- 數學延伸部分（M1/M2）可視作一科完整選修科目",
    "",
    "**額外要求：** 須具備良好的粵語工作能力。",
    "",
    "**計分方法：** 最佳6科 DSE 成績（只計算甲類科目及M1/M2）",
    "",
    "**面試安排：** 設有選擇性面試。面試表現、5**/5*/5級數目及學生學習概覽均為考慮因素。",
    "",
    "**2025年入學統計：**",
    "- Band A 申請人數：123人",
    "- 總申請人數：1,297人",
    "- 錄取名額：27人（100%來自 Band A）",
    "",
    "**2025年入學分數（已獲錄取學生）：**",
    "- 中位數：41分",
    "- 上四分位數：38分",
    "- 下四分位數：39分",
    "",
    "**重考生注意：** 重考科目將會被扣分。只考慮最近三年內的最佳成績。"
]

zh_curriculum = [
    "藥劑學學士課程為期 **4年**，共 **258學分**，包括：",
    "",
    "**學分分配：**",
    "- 藥劑學核心課程：192學分",
    "- 藥劑學選修課程：12學分",
    "- 核心課程：36學分",
    "- 語言課程：18學分",
    "",
    "**第一年：** 藥劑學生基本技能、基礎科學綜合課程（解剖學、生理學及生物化學）、藥劑學實踐研究方法、藥劑學導論、藥物發現、大學核心英語、核心課程",
    "",
    "**第二年：** 藥物化學、劑型設計、身體系統藥劑學系列（心血管及腎臟、腸胃系統、藥物動力學及毒理學、呼吸系統）、藥劑學實踐導論、藥劑學學術溝通、藥劑學實用中文、核心課程",
    "",
    "**第三年：** 先進藥物傳遞系統、藥物分析、藥劑學實踐：社區藥房、身體系統藥劑學系列（內分泌學、中樞神經系統、肌肉骨骼及結締組織疾病、微生物學及傳染病、腫瘤學）",
    "",
    "**第四年：** 研究方法學及研究項目、藥劑學實踐：藥劑法律與倫理、工業藥物開發、生物製藥技術與未來藥物、特殊人群藥物治療學、增潤模組、選修課程",
    "",
    "**選修課程：**",
    "- 分子醫學",
    "- 分子藥理學",
    "- 醫療大數據",
    "- 藥劑學生中醫藥課程",
    "- 心肺及腎臟系統（銜接內外全科醫學士）",
    "",
    "**教學方法：**",
    "- **問題導向學習（PBL）** — 貫穿課程，鼓勵批判性思維及自主學習",
    "- **藥劑學體驗教育計劃（PEEP）** — 累積學習經驗，為進階實踐做好準備",
    "- **病人輔導及溝通技巧訓練** — 在各種情境中逐步掌握病人教育技巧",
    "- **工業藥劑培訓** — 由業界專家教授的實踐經驗",
    "- **中醫藥及補充與替代醫學（CAM）** — 認識本地病人常用的草藥、營養補充品及保健產品",
    "",
    "**實習安排：**",
    "- 於醫院藥房、社區藥房及製藥業輪換（最後一年每個場景至少一星期）",
    "- 在學術人員指導下完成專門領域的研究項目",
    "- 增潤模組提供於學術機構或非牟利社區服務機構的定制實習",
    "",
    "**跨專業學習：**",
    "- 與醫學、護理及中醫藥學生合作的病人護理項目（PCP）"
]

zh_career = [
    "課程獲香港 **藥劑業及毒藥管理局** 認可。畢業生完成學位及 **一年實習** 後，符合資格成為香港 **註冊藥劑師**。",
    "",
    "**就業出路：**",
    "",
    "**1. 社區藥房**",
    "- 連鎖及獨立藥房的社區藥劑師",
    "- 基層醫療及業務管理",
    "- 替假藥劑師",
    "- 獸醫藥劑師",
    "",
    "**2. 醫院藥房**",
    "- 醫院管理局及私立醫院",
    "- 配藥部及靜脈藥物調配服務（PIVAS）",
    "- 臨床／專科藥劑師（如兒科、腫瘤科）",
    "- 放射性藥物學",
    "- 醫學資訊及臨床試驗支援",
    "- 藥物採購",
    "",
    "**3. 製藥工業**",
    "- 本地製造商及跨國企業",
    "- 生產及供應、品質保證（QA）",
    "- 藥物研發（R&D）",
    "- 法規事務、業務發展",
    "- 醫學資訊、銷售及市場推廣",
    "- 藥物警戒、臨床試驗管理",
    "",
    "**4. 政府及公共衛生**",
    "- 衞生署／藥物辦公室",
    "- 政策規劃、藥物警戒",
    "- 巡查、藥物註冊",
    "- 臨床服務、公共衛生",
    "",
    "**5. 學術界及科研**",
    "- 大學及高等教育機構",
    "- 藥劑學教育（培訓師或技術員）",
    "- 科學研究、健康推廣、知識轉移",
    "- 進修（博士、醫學或研究學位）",
    "",
    "**6. 其他職位**",
    "- 醫學撰稿人／編輯",
    "- 非牟利機構（醫療項目統籌、安老院駐院藥劑師）",
    "",
    "**進修途徑：**",
    "- 高等藥劑學碩士（授課式研究生）",
    "- 藥劑學相關研究（哲學碩士／博士）",
    "- 畢業生可選修銜接內外全科醫學士課程"
]

zh_campus = [
    "**校園及設施：**",
    "- 課程設於港大本部校園（薄扶林）",
    "- 配備先進設備的藥物化學、劑型設計及藥物分析實驗室",
    "- 病人輔導訓練的臨床模擬設施",
    "",
    "**學生生活：**",
    "- 每年約35人的收生規模",
    "- 藥劑學體驗教育計劃（PEEP）提供持續的實踐場景接觸",
    "- 培養專業精神、倫理、解難能力、團隊合作及終身學習承諾",
    "- 增潤模組提供國際交流機會",
    "- 與醫學、護理及中醫藥學生的跨專業學習",
    "",
    "**實習機會：**",
    "- 學期期間於各種藥劑場景獲得工作經驗",
    "- 於醫院藥房、社區藥房及製藥業輪換",
    "- 學術人員指導下的專門領域研究項目",
    "- 於香港最大型社區藥房連鎖店實習",
    "",
    "**學生分享：**",
    "「從在社區藥房為常見疾病提供專業建議，到為危及生命的疾病研究新療法，藥劑師每天都在不同方面影響人們的生活。這是一個極具多樣性的專業，我很榮幸能成為其中一員。」— 許詠妮，藥劑學學士2015，衞生署藥物辦公室藥劑師",
    "",
    "「運用我們的專業藥物知識為病人優化醫療方案，正是藥劑師工作的意義所在。」— 朱小姐，藥理學及藥學系高級講師"
]

zh_competitiveness = [
    "**入學競爭力分析：**",
    "",
    "**競爭程度：** 極高 — 每個學額有4.6位 Band A 申請者（123人 ÷ 27個名額）",
    "",
    "**主要數據（2025年）：**",
    "- 總申請人數：1,297人",
    "- Band A 申請人數：123人",
    "- 錄取名額：27人（100%來自 Band A）",
    "- 首年學額：35人（部分保留予非 JUPAS 申請者）",
    "",
    "**歷史趨勢：**",
    "- 近年錄取名額維持於27–32人",
    "- 100%錄取持續來自 Band A",
    "- 總申請人數穩定於1,200–1,400人",
    "",
    "**分數分析：**",
    "- 中位數：41分（最佳6科）",
    "- 約相等於6科達5*555555或更佳成績",
    "- 最佳6科計分法重視廣度 — 不能靠5科掩飾第6科的弱點",
    "- 英國語文第4級是嚴格要求（高於一般課程的第3級）",
    "",
    "**成功入讀的關鍵因素：**",
    "1. **必須放 Band A** — 近年沒有 Band B至E的錄取個案",
    "2. **化學是必修科** — 兩科選修中一科必須為化學，且達第3級或以上",
    "3. **英國語文第4級** — 高於一般港大要求；英文未達標者自動不符合資格",
    "4. **粵語能力** — 社區藥房實踐必需",
    "5. **面試表現** — 選擇性面試評估溝通技巧、動機及對藥劑專業的理解",
    "6. **學生學習概覽** — 相關經驗（如藥房義工、科學研究）可增強申請",
    "7. **組合科學／綜合科學** — 以往成績亦獲考慮"
]

zh_alumni = [
    "**知名教職員：**",
    "",
    "- **陳教授** — 醫學院副院長（健康科學教育），藥理學及藥學系教授。臨床藥劑學及藥物治療學領域的頂尖研究者。",
    "- **朱小姐** — 藥理學及藥學系高級講師。臨床藥劑實踐及病人護理專家。",
    "",
    "**傑出校友：**",
    "- **許詠妮**（藥劑學學士2015）— 衞生署藥物辦公室藥劑師。「從在社區藥房為常見疾病提供專業建議，到為危及生命的疾病研究新療法，藥劑師每天都在不同方面影響人們的生活。」",
    "",
    "**專業認可：**",
    "- 課程獲香港藥劑業及毒藥管理局認可",
    "- 畢業生完成一年實習後可成為註冊藥劑師",
    "- 港大醫學院位列全球頂尖醫學院之一，擁有135年以上歷史",
    "",
    "**研究卓越：**",
    "- 藥理學及藥學系於藥物發現、藥物治療學及臨床藥劑學進行前沿研究",
    "- 所有四年級學生須在學術人員指導下完成研究項目",
    "- 可進修研究式研究生課程（哲學碩士／博士）"
]

zh_scholarships = [
    "**港大入學獎學金：**",
    "- **港大基金入學獎學金** — 頒予 DSE 成績卓越的 JUPAS 申請人",
    "- **港大傑出學生獎學金** — 頒予核心科目及選修科目均獲5**的學生",
    "",
    "**學院獎學金：**",
    "- 醫學院設有多項獎學金，獎勵學業成績優異的學生",
    "- 藥劑學生研究項目獎學金",
    "",
    "**政府資助：**",
    "- 專上學生資助計劃（TSFS）— 經入息審查的助學金及貸款",
    "- 免入息審查貸款計劃（NLS）— 所有合資格學生均可申請的低息貸款",
    "",
    "**其他機會：**",
    "- 增潤模組國際實習交流獎學金",
    "- 本科生研究項目資助",
    "- 製藥公司贊助獎學金"
]

zh_tips = [
    "**Ace Sir 港大藥劑學學士攻略 — 9個實戰貼士：**",
    "",
    "**1. Band A 是必須的**",
    "100%錄取來自 Band A 申請者。若藥劑學是你的目標，必須將 JS6494 放在 Band A，沒有例外。",
    "",
    "**2. 化學是你的成敗關鍵**",
    "化學達第3級是強制要求，不可妥協。建議目標為第5級或以上以增強競爭力。課程高度依賴化學（藥物化學、劑型設計、藥物分析）。若化學是你的弱項，請重新考慮此課程。",
    "",
    "**3. 英國語文第4級是硬門檻**",
    "與一般港大課程要求英國語文第3級不同，藥劑學要求第4級。這已篩走很多申請者。若英文未達第4級，無論其他科目成績如何都自動不符合資格。務必重點投資英文準備。",
    "",
    "**4. 目標41分或以上（最佳6科）**",
    "中位數為41分（最佳6科）。這意味著6科約需達5*555555或更佳。與最佳5科課程不同，你不能用5科掩飾第6科的弱點。每科都很重要，力求各科成績均衡。",
    "",
    "**5. 建立藥劑學導向的學生學習概覽**",
    "- 於社區藥房當義工（如屈臣氏、萬寧或獨立藥房）",
    "-  shadow 藥劑師一天以了解專業實況",
    "- 閱讀藥物發現及製藥新聞（如 FDA 批核、新療法）",
    "- 參與化學或生物比賽",
    "- 展示對藥劑師醫療角色的理解（不只是「派藥」）",
    "",
    "**6. 準備選擇性面試**",
    "並非所有申請者都獲面試機會。若被選中，預計會被問及：",
    "- 「為何選擇藥劑學而非醫學／護理？」（須有真誠具體的答案）",
    "- 倫理情境題（如病人要求不適當藥物）",
    "- 當前醫療議題（如抗生素耐藥性、鴉片類藥物危機）",
    "- 你對藥劑師角色演變的理解（臨床藥劑，不只是配藥）",
    "- 溝通技巧評估（病人輔導情境）",
    "",
    "**7. 粵語很重要**",
    "須具備良好的粵語工作能力。香港社區藥房大部分病人說粵語。若粵語不流利，請考慮能否有效輔導病人。這是實際工作要求，不只是形式上的條件。",
    "",
    "**8. 了解4年學位 + 1年實習的路徑**",
    "學位為4年，但須額外1年實習才能成為註冊藥劑師。這意味著：",
    "- 總共5年才取得正式註冊",
    "- 實習崗位具競爭性（醫管局、私立醫院、連鎖藥房）",
    "- 註冊藥劑師起薪點吸引（約5–6萬港元／月）",
    "- 可晉升為專科藥劑師",
    "",
    "**9. 要有後備方案**",
    "只有約27個 JUPAS 學額，123位 Band A 申請者，競爭非常激烈。建議考慮：",
    "- 中文大學藥劑學（如有開辦）",
    "- 生物醫學或生物化學作為相關替代選擇",
    "- 化學，輔以製藥應用興趣",
    "- 海外藥劑學院（英國、澳洲）如有資源",
    "- 記住：藥劑學畢業生亦可從事科研、工業或學術工作 — 不限於社區／醫院藥房"
]

details = {
    "code": "JS6494",
    "university": "香港大學",
    "en": {
        "sections": {
            "admission": {"title": "Eligibility & Admission Criteria (DSE)", "content": en_admission},
            "curriculum": {"title": "Programme Structure & Curriculum", "content": en_curriculum},
            "career": {"title": "Career Pathways & Prospects", "content": en_career},
            "campus": {"title": "Campus Life & Student Experience", "content": en_campus},
            "competitiveness": {"title": "Admission Competitiveness Analysis", "content": en_competitiveness},
            "alumni": {"title": "Notable Alumni & Faculty", "content": en_alumni},
            "scholarships": {"title": "Scholarships & Financial Aid", "content": en_scholarships},
            "tips": {"title": "Ace Sir's HKU BPharm Strategy", "content": en_tips}
        }
    },
    "zh": {
        "sections": {
            "admission": {"title": "入學要求與計分詳情 (DSE)", "content": zh_admission},
            "curriculum": {"title": "課程結構與內容", "content": zh_curriculum},
            "career": {"title": "職業前景與出路", "content": zh_career},
            "campus": {"title": "校園生活與學生體驗", "content": zh_campus},
            "competitiveness": {"title": "入學競爭力分析", "content": zh_competitiveness},
            "alumni": {"title": "知名校友及教職員", "content": zh_alumni},
            "scholarships": {"title": "獎學金及經濟援助", "content": zh_scholarships},
            "tips": {"title": "Ace Sir 港大藥劑學學士攻略", "content": zh_tips}
        }
    }
}

container.upsert_item({**programme, "id": f"prog_{programme['code']}", "pk": "programmes", "type": "programme"})
container.upsert_item({**details, "id": f"detail_{details['code']}", "pk": "details", "type": "programme_detail"})
print(f"[Seed] {programme['code']} - {programme['nameEn']} / {programme['nameZh']} - Done!")
