// Auto-generated JUPAS programme database
// Total programmes: 357
// Generated: 2026-05-17

export const PROGRAM_CATEGORIES = {
    'Architecture & Built Environment': '建築及建造環境',
    'Arts': '文學及人文科學',
    'Business': '商學及管理',
    'Communication & Media': '傳理及媒體',
    'Computer & Data Science': '計算機及數據科學',
    'Design': '設計及視覺藝術',
    'Education': '教育學',
    'Engineering': '工程學',
    'Health Science': '健康科學及護理',
    'Interdisciplinary / Broad-based': '跨學科及綜合課程',
    'Law': '法律學',
    'Medicine': '醫學及牙醫學',
    'Science': '理學',
    'Social Science': '社會科學',
};

export const UNIVERSITY_SHORT_NAMES = {
  'The Hong Kong Polytechnic University': 'PolyU',
  '嶺南大學': 'Lingnan',
  '香港中文大學': 'CUHK',
  '香港城市大學': 'CityU',
  '香港大學': 'HKU',
  '香港教育大學': 'EdUHK',
  '香港浸會大學': 'HKBU',
  '香港理工大學': 'PolyU',
  '香港科技大學': 'HKUST',
  '香港都會大學': 'HKMU',
};

export function getUniversityLabel(university, language = 'zh') {
  if (!university) return '';
  const short = UNIVERSITY_SHORT_NAMES[university] || university;
  if (language === 'en') return short;
  return university;
}

export const JUPAS_PROGRAMS = [
  { id: 'JS1000', code: 'JS1000', name: 'BSc Computational Finance and Financial Technology', nameZh: '理學士(計算金融及金融科技)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1001', code: 'JS1001', name: 'BBA Global Business', nameZh: '工商管理學士(環球商業)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1002', code: 'JS1002', name: 'BBA Accountancy', nameZh: '工商管理學士(會計)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1005', code: 'JS1005', name: 'BBA Management', nameZh: '工商管理學士(管理學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1007', code: 'JS1007', name: 'BBA Marketing', nameZh: '工商管理學士(市場學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1012', code: 'JS1012', name: 'Economics and Finance', nameZh: '經濟及金融', university: '香港城市大學', category: 'Business' },
  { id: 'JS1013', code: 'JS1013', name: 'BBA Business Economics', nameZh: '工商管理學士(商業經濟)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1014', code: 'JS1014', name: 'BBA Finance', nameZh: '工商管理學士(金融)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1017', code: 'JS1017', name: 'Intelligent Information Systems', nameZh: '智能資訊系統學', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1018', code: 'JS1018', name: 'BBA Global Business Systems Management', nameZh: '工商管理學士(環球商業系統管理)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1019', code: 'JS1019', name: 'BBA Artificial Intelligence in Business', nameZh: '工商管理學士(商業人工智能)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1026', code: 'JS1026', name: 'BBA Business Decision Analytics', nameZh: '工商管理學士(商業決策分析)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1027', code: 'JS1027', name: 'BBA Global Operations Management', nameZh: '工商管理學士(環球營運管理)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1040', code: 'JS1040', name: 'Creative Arts and Technology Excellence', nameZh: '卓越創藝與科技課程', university: '香港城市大學', category: 'Design' },
  { id: 'JS1041', code: 'JS1041', name: 'Creative Media', nameZh: '創意媒體', university: '香港城市大學', category: 'Design' },
  { id: 'JS1042', code: 'JS1042', name: 'BA Creative Media', nameZh: '文學士(創意媒體)', university: '香港城市大學', category: 'Design' },
  { id: 'JS1043', code: 'JS1043', name: 'BSc Creative Media', nameZh: '理學士(創意媒體)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1044', code: 'JS1044', name: 'BAS New Media', nameZh: '文理學士(新媒體)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1050', code: 'JS1050', name: 'International Sustainability Programme for Innovation, Research & Entrepreneurship', nameZh: '環球可持續發展科創課程', university: '香港城市大學', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS1051', code: 'JS1051', name: 'Energy and Environment', nameZh: '能源及環境學', university: '香港城市大學', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS1052', code: 'JS1052', name: 'BEng Environmental Science and Engineering and BBA Finance', nameZh: '工學士(環境科學及工程學)與工商管理學士(金融)', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1053', code: 'JS1053', name: 'BSc Environment and Sustainable Business', nameZh: '理學士(環境及可持續發展商業)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1061', code: 'JS1061', name: 'Bachelor of Laws', nameZh: '法律學學士', university: '香港城市大學', category: 'Law' },
  { id: 'JS1062', code: 'JS1062', name: 'Bachelor of Laws and BBA Accountancy', nameZh: '法律學學士與工商管理學士(會計)', university: '香港城市大學', category: 'Law' },
  { id: 'JS1070', code: 'JS1070', name: 'AI, Computing and Transformation', nameZh: '人工智能・計算・突破課程', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1071', code: 'JS1071', name: 'Data Science', nameZh: '數據科學', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1072', code: 'JS1072', name: 'BSc Data Science', nameZh: '理學士(數據科學)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1074', code: 'JS1074', name: 'BSc Data and Systems Engineering', nameZh: '理學士(數據與系統工程)', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1102', code: 'JS1102', name: 'BSocSc International Relations and Global Affairs', nameZh: '社會科學學士(國際關係及全球事務)', university: '香港城市大學', category: 'Social Science' },
  { id: 'JS1103', code: 'JS1103', name: 'BA Chinese and History', nameZh: '文學士(中文及歷史)', university: '香港城市大學', category: 'Arts' },
  { id: 'JS1104', code: 'JS1104', name: 'BA English', nameZh: '文學士(英語語言)', university: '香港城市大學', category: 'Arts' },
  { id: 'JS1106', code: 'JS1106', name: 'Media and Communication', nameZh: '媒體與傳播', university: '香港城市大學', category: 'Communication & Media' },
  { id: 'JS1108', code: 'JS1108', name: 'BSocSc Public Affairs and Management', nameZh: '社會科學學士(公共事務與管理)', university: '香港城市大學', category: 'Social Science' },
  { id: 'JS1109', code: 'JS1109', name: 'BA Linguistics and Language Applications', nameZh: '文學士(語言學及語言應用)', university: '香港城市大學', category: 'Arts' },
  { id: 'JS1111', code: 'JS1111', name: 'BSocSc Crime Science', nameZh: '社會科學學士(犯罪科學)', university: '香港城市大學', category: 'Social Science' },
  { id: 'JS1112', code: 'JS1112', name: 'BSocSc Psychology', nameZh: '社會科學學士(心理學)', university: '香港城市大學', category: 'Social Science' },
  { id: 'JS1113', code: 'JS1113', name: 'BSocSc Social Work', nameZh: '社會科學學士(社會工作)', university: '香港城市大學', category: 'Social Science' },
  { id: 'JS1123', code: 'JS1123', name: 'BSocSc Crime Science and Bachelor of Laws', nameZh: '社會科學學士(犯罪科學)與法律學學士', university: '香港城市大學', category: 'Law' },
  { id: 'JS1200', code: 'JS1200', name: 'Global Research Enrichment and Technopreneurship', nameZh: '環球精研與科創課程', university: '香港城市大學', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS1201', code: 'JS1201', name: 'Architecture and Civil Engineering', nameZh: '建築學及土木工程學', university: '香港城市大學', category: 'Architecture & Built Environment' },
  { id: 'JS1202', code: 'JS1202', name: 'BSc Chemistry', nameZh: '理學士(化學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1204', code: 'JS1204', name: 'BSc Computer Science', nameZh: '理學士(計算機科學)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1205', code: 'JS1205', name: 'Electrical Engineering', nameZh: '電機工程學', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1206', code: 'JS1206', name: 'BSc Computing Mathematics', nameZh: '理學士(計算數學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1207', code: 'JS1207', name: 'Mechanical Engineering', nameZh: '機械工程學', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1208', code: 'JS1208', name: 'BSc Physics', nameZh: '理學士(物理學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1210', code: 'JS1210', name: 'BEng Materials Science and Engineering', nameZh: '工學士(材料科學及工程)', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1211', code: 'JS1211', name: 'BEng Biomedical Engineering', nameZh: '工學士(生物醫學工程)', university: '香港城市大學', category: 'Medicine' },
  { id: 'JS1216', code: 'JS1216', name: 'BEng Intelligent Manufacturing Engineering', nameZh: '工學士(智能製造工程學)', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1217', code: 'JS1217', name: 'Pathway for Research, Innovation, and Multinational Engineering', nameZh: '研究、創新和環球工程課程', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1218', code: 'JS1218', name: 'BSc Cybersecurity', nameZh: '理學士(網絡安全)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1219', code: 'JS1219', name: 'BEng Innovation and Enterprise Engineering', nameZh: '工學士(創新與企業工程)', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1221', code: 'JS1221', name: 'BSc Computer Science and BSc Computational Finance and Financial Technology', nameZh: '理學士(計算機科學)與理學士(計算金融及金融科技)', university: '香港城市大學', category: 'Computer & Data Science' },
  { id: 'JS1300', code: 'JS1300', name: 'Integrative Bioscience & Bioengineering Programme', nameZh: '綜合生物科學與生物工程課程', university: '香港城市大學', category: 'Engineering' },
  { id: 'JS1801', code: 'JS1801', name: 'Bachelor of Veterinary Medicine', nameZh: '獸醫學學士', university: '香港城市大學', category: 'Medicine' },
  { id: 'JS1805', code: 'JS1805', name: 'Biomedical Sciences', nameZh: '生物醫學', university: '香港城市大學', category: 'Medicine' },
  { id: 'JS1806', code: 'JS1806', name: 'BSc Biological Sciences', nameZh: '理學士(生物科學)', university: '香港城市大學', category: 'Science' },
  { id: 'JS1807', code: 'JS1807', name: 'BSc Biomedical Sciences', nameZh: '理學士(生物醫學)', university: '香港城市大學', category: 'Medicine' },
  { id: 'JS2020', code: 'JS2020', name: 'Bachelor of Arts (Hons) (Chinese Language and Literature / Creative and Professional Writing / English Language and Literature / Humanities / Translation)', nameZh: '文學士(榮譽) (中國語言文學 / 創意及專業寫作 / 英國語言文學 / 人文學 / 翻譯學)', university: '香港浸會大學', category: 'Arts' },
  { id: 'JS2025', code: 'JS2025', name: 'Bachelor of Arts (Hons) in Religion, Philosophy and Ethics', nameZh: '宗教、哲學及倫理文學士(榮譽)', university: '香港浸會大學', category: 'Arts' },
  { id: 'JS2060', code: 'JS2060', name: 'Bachelor of Arts (Hons) / Bachelor of Music (Hons) (Music / Creative Industries)', nameZh: '文學士(榮譽) / 音樂學士(榮譽) (音樂 / 創意產業)', university: '香港浸會大學', category: 'Arts' },
  { id: 'JS2110', code: 'JS2110', name: 'Bachelor of Business Administration (Hons) - Accounting Concentration', nameZh: '工商管理學士(榮譽) - 會計學專修', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2120', code: 'JS2120', name: 'Bachelor of Business Administration (Hons)', nameZh: '工商管理學士(榮譽)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2310', code: 'JS2310', name: 'Bachelor of Communication (Hons) (Journalism and Digital Media / Public Relations and Advertising)', nameZh: '傳理學學士(榮譽) (新聞與數碼媒體 / 公關及廣告)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2330', code: 'JS2330', name: 'Bachelor of Arts (Hons) in Film and Television', nameZh: '電影電視文學士(榮譽)', university: '香港浸會大學', category: 'Communication & Media' },
  { id: 'JS2340', code: 'JS2340', name: 'Bachelor of Fine Arts (Hons) in Acting for Global Screen', nameZh: '環球螢幕演技藝術學士(榮譽)', university: '香港浸會大學', category: 'Communication & Media' },
  { id: 'JS2370', code: 'JS2370', name: 'Bachelor of Communication (Hons) in Game Design and Animation', nameZh: '傳理學學士(榮譽) - 遊戲設計與動畫主修', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2410', code: 'JS2410', name: 'Bachelor of Chinese Medicine and Bachelor of Science (Hons) in Biomedical Science', nameZh: '中醫學學士及生物醫學理學士(榮譽)', university: '香港浸會大學', category: 'Medicine' },
  { id: 'JS2420', code: 'JS2420', name: 'Bachelor of Pharmacy (Hons) in Chinese Medicine', nameZh: '中藥學學士(榮譽)', university: '香港浸會大學', category: 'Medicine' },
  { id: 'JS2510', code: 'JS2510', name: 'Bachelor of Science (Hons)', nameZh: '理學士(榮譽)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2610', code: 'JS2610', name: 'Bachelor of Arts (Hons) / Bachelor of Social Sciences (Hons) (European Studies [French/German Stream] / Geography/ Global and China Studies/ Government and International Studies/ History/ Sociology)', nameZh: '文學士(榮譽) / 社會科學學士(榮譽) (歐洲研究 [法文/德文] / 地理 / 全球及中國研究 / 政治及國際關係學 / 歷史 / 社會學)', university: '香港浸會大學', category: 'Social Science' },
  { id: 'JS2620', code: 'JS2620', name: 'Bachelor of Arts (Hons) in Physical Education and Recreation Management', nameZh: '體育及康樂管理文學士(榮譽)', university: '香港浸會大學', category: 'Education' },
  { id: 'JS2660', code: 'JS2660', name: 'Bachelor of Social Work (Hons)', nameZh: '社會工作學士(榮譽)', university: '香港浸會大學', category: 'Social Science' },
  { id: 'JS2810', code: 'JS2810', name: 'Bachelor of Arts (Hons) in Visual Arts', nameZh: '視覺藝術文學士(榮譽)', university: '香港浸會大學', category: 'Design' },
  { id: 'JS2910', code: 'JS2910', name: 'Bachelor of Science (Hons) in Business Computing and Data Analytics', nameZh: '商業計算及數據分析理學士(榮譽)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2920', code: 'JS2920', name: 'Bachelor of Arts and Science (Hons) in Arts and Technology', nameZh: '藝術及科技文理學士(榮譽)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS2930', code: 'JS2930', name: 'Bachelor of Arts (Hons) in Business Administration (Global Entertainment)', nameZh: '工商管理文學士(榮譽)(全球娛樂)', university: '香港浸會大學', category: 'Business' },
  { id: 'JS2940', code: 'JS2940', name: 'Bachelor of Social Sciences (Hons) / Bachelor of Science (Hons) in Innovation in Health and Social Well-Being', nameZh: '創新醫療及社會健康社會科學學士(榮譽) / 理學士(榮譽)', university: '香港浸會大學', category: 'Health Science' },
  { id: 'JS2950', code: 'JS2950', name: 'Bachelor of Arts, Science and Technology (Hons) in Individualised Major', nameZh: '文理及科技學士(榮譽)自訂主修', university: '香港浸會大學', category: 'Arts' },
  { id: 'JS2960', code: 'JS2960', name: 'Bachelor of Arts and Science (Hons) in Digital Futures and Humanities', nameZh: '數位未來與人文學科文理學士(榮譽)', university: '香港浸會大學', category: 'Science' },
  { id: 'JS3000', code: 'JS3000', name: "Bachelor's Degree Scheme in Interdisciplinary Studies", nameZh: '跨學科組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS3003', code: 'JS3003', name: 'BBA Scheme in Business Administration', nameZh: '工商管理組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Business' },
  { id: 'JS3004', code: 'JS3004', name: "Bachelor's Degree Scheme in Construction and Environment", nameZh: '建設及環境組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3005', code: 'JS3005', name: "Bachelor's Degree Scheme in Engineering", nameZh: '工程學科組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3006', code: 'JS3006', name: "Bachelor's Degree Scheme in Computer and Mathematical Sciences", nameZh: '計算機及數學科學組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Computer & Data Science' },
  { id: 'JS3007', code: 'JS3007', name: "Bachelor's Degree Scheme in Humanities", nameZh: '人文學科組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Arts' },
  { id: 'JS3008', code: 'JS3008', name: "Bachelor's Degree Scheme in Science", nameZh: '理學組合學士課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3011', code: 'JS3011', name: 'BSc Scheme in Biotechnology and Chemical Technology', nameZh: '生物科技及化學科技(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3030', code: 'JS3030', name: 'BSc in Physics with Secondary Major in AIDA / IE', nameZh: '物理學(榮譽)理學士副主修AIDA/IE', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3050', code: 'JS3050', name: 'BA Scheme in Fashion', nameZh: '時裝(榮譽)文學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Design' },
  { id: 'JS3060', code: 'JS3060', name: 'BBA Scheme in Accounting and Finance', nameZh: '會計及金融(榮譽)工商管理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3070', code: 'JS3070', name: 'BBA Scheme in Global Business and Logistics', nameZh: '環球商業及物流(榮譽)工商管理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3080', code: 'JS3080', name: 'BBA Scheme in Management and Marketing', nameZh: '管理及市場學(榮譽)工商管理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3130', code: 'JS3130', name: 'BSc Scheme in Spatial Data Science and Smart Cities', nameZh: '空間數據科學及智慧城市(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3140', code: 'JS3140', name: 'BEng Scheme in Aviation Engineering', nameZh: '航空工程學(榮譽)工學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3150', code: 'JS3150', name: 'BSc in Biomedical Engineering', nameZh: '生物醫學工程(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Medicine' },
  { id: 'JS3160', code: 'JS3160', name: 'BSc in Sports Science and Technology', nameZh: '體育科技(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3170', code: 'JS3170', name: 'BEng Scheme in Electrical Engineering', nameZh: '電機工程學(榮譽)工學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3180', code: 'JS3180', name: 'BEng/BSc Scheme in Information and AI Engineering', nameZh: '資訊及人工智能工程學(榮譽)工學士/理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Computer & Data Science' },
  { id: 'JS3211', code: 'JS3211', name: 'BEng in Building Sciences and Engineering', nameZh: '建築科學及工程學(榮譽)工學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3214', code: 'JS3214', name: 'BSc in Architectural Studies', nameZh: '建築學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3220', code: 'JS3220', name: 'BSc Scheme in Applied Mathematics and Finance Analytics', nameZh: '應用數學及金融分析(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3223', code: 'JS3223', name: 'BSc Scheme in Data Science and Artificial Intelligence', nameZh: '數據科學及人工智能(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Computer & Data Science' },
  { id: 'JS3236', code: 'JS3236', name: 'BEng Scheme in Product Innovation and Smart Manufacturing', nameZh: '產品創新及智能製造(榮譽)工學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3237', code: 'JS3237', name: 'BSc Scheme in Intelligent Supply Chain and Engineering Management', nameZh: '智能供應鏈及工程管理(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3240', code: 'JS3240', name: 'BA in English and Applied Linguistics', nameZh: '英文及應用語言學(榮譽)文學士', university: 'The Hong Kong Polytechnic University', category: 'Arts' },
  { id: 'JS3242', code: 'JS3242', name: 'BSc in Speech Therapy', nameZh: '言語治療(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3243', code: 'JS3243', name: 'BSc in Language Science and Technology', nameZh: '語言科學及技術(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3250', code: 'JS3250', name: 'BA Scheme in Applied Social Sciences', nameZh: '應用社會科學(榮譽)文學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Social Science' },
  { id: 'JS3255', code: 'JS3255', name: 'BSc Scheme in Food Science and Nutrition', nameZh: '食品科學及營養學(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3290', code: 'JS3290', name: 'BSc in Optometry', nameZh: '眼科視光學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3310', code: 'JS3310', name: 'BSc Scheme in Hotel and Tourism Management', nameZh: '酒店及旅遊管理(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Science' },
  { id: 'JS3320', code: 'JS3320', name: 'BA in Chinese History and Culture', nameZh: '中國歷史及文化(榮譽)文學士', university: 'The Hong Kong Polytechnic University', category: 'Arts' },
  { id: 'JS3337', code: 'JS3337', name: 'BSc in Mental Health Nursing', nameZh: '精神健康護理學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3375', code: 'JS3375', name: 'BEng in Environmental Engineering and Sustainable Development', nameZh: '環境工程及可持續發展學(榮譽)工學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3478', code: 'JS3478', name: 'BSc in Medical Laboratory Science', nameZh: '醫療化驗科學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3569', code: 'JS3569', name: 'BA Scheme in Design', nameZh: '設計學(榮譽)文學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Design' },
  { id: 'JS3612', code: 'JS3612', name: 'BSc in Radiography', nameZh: '放射學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3624', code: 'JS3624', name: 'BSc in Occupational Therapy', nameZh: '職業治療學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3636', code: 'JS3636', name: 'BSc in Physiotherapy', nameZh: '物理治療學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3648', code: 'JS3648', name: 'BSc in Nursing', nameZh: '護理學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Health Science' },
  { id: 'JS3739', code: 'JS3739', name: 'BEng in Civil Engineering', nameZh: '土木工程學(榮譽)工學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3741', code: 'JS3741', name: 'BEng Scheme in Mechanical Engineering', nameZh: '機械工程學(榮譽)工學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Engineering' },
  { id: 'JS3789', code: 'JS3789', name: 'BSc in Surveying', nameZh: '地產及建設測量學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3791', code: 'JS3791', name: 'BSc in Building Engineering and Management', nameZh: '建築工程及管理學(榮譽)理學士', university: 'The Hong Kong Polytechnic University', category: 'Architecture & Built Environment' },
  { id: 'JS3868', code: 'JS3868', name: 'BSc Scheme in Computing and AI', nameZh: '電子計算及人工智能(榮譽)理學士組合課程', university: 'The Hong Kong Polytechnic University', category: 'Computer & Data Science' },
  { id: 'JS4006', code: 'JS4006', name: 'Anthropology', nameZh: '人類學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4018', code: 'JS4018', name: 'Chinese Language and', nameZh: '中國語言及文學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4032', code: 'JS4032', name: 'English', nameZh: '英文', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4044', code: 'JS4044', name: 'Fine Arts', nameZh: '藝術', university: '香港中文大學', category: 'Design' },
  { id: 'JS4056', code: 'JS4056', name: 'History', nameZh: '歷史', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4068', code: 'JS4068', name: 'Japanese Studies', nameZh: '日本研究', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4070', code: 'JS4070', name: 'Linguistics', nameZh: '語言學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4082', code: 'JS4082', name: 'Music', nameZh: '音樂', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4094', code: 'JS4094', name: 'Philosophy', nameZh: '哲學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4100', code: 'JS4100', name: 'Public Humanities', nameZh: '公共人文學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4109', code: 'JS4109', name: 'Religious Studies', nameZh: '宗教研究', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4111', code: 'JS4111', name: 'Theology', nameZh: '神學', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4123', code: 'JS4123', name: 'Translation', nameZh: '翻譯', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4136', code: 'JS4136', name: 'Chinese Studies', nameZh: '中國研究', university: '香港中文大學', category: 'Arts' },
  { id: 'JS4202', code: 'JS4202', name: 'Integrated Bachelor of Business Administration', nameZh: '工商管理學士綜合課程', university: '香港中文大學', category: 'Science' },
  { id: 'JS4214', code: 'JS4214', name: 'Global Business Studies', nameZh: '環球商業學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4226', code: 'JS4226', name: 'Hospitality and Real Estate', nameZh: '酒店旅遊及房地產', university: '香港中文大學', category: 'Business' },
  { id: 'JS4238', code: 'JS4238', name: 'Insurance, Financial and Actuarial Analysis', nameZh: '保險、金融與精算學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4240', code: 'JS4240', name: 'Professional Accountancy', nameZh: '專業會計學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4252', code: 'JS4252', name: 'Quantitative Finance', nameZh: '計量金融學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4254', code: 'JS4254', name: 'Programme in Global Economics', nameZh: '環球經濟與金融跨學科主修課程', university: '香港中文大學', category: 'Business' },
  { id: 'JS4264', code: 'JS4264', name: 'BBA(IBBA) – JD Double Degree', nameZh: '工商管理學士（工商管理學士綜合課程）及法律博士雙學位課程', university: '香港中文大學', category: 'Law' },
  { id: 'JS4276', code: 'JS4276', name: 'Quantitative Finance and Risk Management Science', nameZh: '計量金融學及風險管理科學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4320', code: 'JS4320', name: 'Human Movement Science and', nameZh: '人體運動科學與健康研究', university: '香港中文大學', category: 'Science' },
  { id: 'JS4329', code: 'JS4329', name: 'Physical Education, Exercise', nameZh: '健康與體育運動科學', university: '香港中文大學', category: 'Science' },
  { id: 'JS4331', code: 'JS4331', name: 'BA (Chinese Language Studies) and BEd (Chinese Language Education)', nameZh: '文學士 (中國語文研究) 及教育學士 (中國語文教育)', university: '香港中文大學', category: 'Education' },
  { id: 'JS4343', code: 'JS4343', name: 'BA (English Studies) and BEd', nameZh: '文學士(英國語文研究)及教育學士(英國語文教育)', university: '香港中文大學', category: 'Education' },
  { id: 'JS4361', code: 'JS4361', name: 'BEd in Mathematics and Mathematics Education', nameZh: '教育學士(數學及數學教育)', university: '香港中文大學', category: 'Science' },
  { id: 'JS4372', code: 'JS4372', name: 'BEd in Early Childhood Education', nameZh: '教育學士(幼兒教育)', university: '香港中文大學', category: 'Education' },
  { id: 'JS4386', code: 'JS4386', name: 'BSc in Learning Design and Technology', nameZh: '理學士（學習設計與科技）', university: '香港中文大學', category: 'Science' },
  { id: 'JS4408', code: 'JS4408', name: 'Mechanical and Automation Engineering', nameZh: '機械與自動化工程學', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4412', code: 'JS4412', name: 'Computer Science and Engineering', nameZh: '計算機科學與工程', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4416', code: 'JS4416', name: 'Computational Data Science', nameZh: '計算數據科學', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4428', code: 'JS4428', name: 'Financial Technology', nameZh: '金融科技學', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4434', code: 'JS4434', name: 'Electronic Engineering', nameZh: '電子工程學', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4446', code: 'JS4446', name: 'Information Engineering', nameZh: '信息工程學', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4458', code: 'JS4458', name: 'Systems Engineering and Engineering Management', nameZh: '系統工程與工程管理', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4460', code: 'JS4460', name: 'Biomedical Engineering', nameZh: '生物醫學工程學', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4462', code: 'JS4462', name: 'Energy and Environmental Engineering', nameZh: '能源與環境工程學', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4468', code: 'JS4468', name: 'Artificial Intelligence: Systems and Technologies', nameZh: '人工智能：系統與科技', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4470', code: 'JS4470', name: 'Materials Science and', nameZh: '材料科學與工程學', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4501', code: 'JS4501', name: 'Bachelor of Medicine and Bachelor of Surgery (MBChB)', nameZh: '內外全科醫學士', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4502', code: 'JS4502', name: 'Global Physician-Leadership', nameZh: '內外全科醫學士課程環球醫學領袖培訓專修組別', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4513', code: 'JS4513', name: 'Bachelor of Nursing', nameZh: '護理學士', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4525', code: 'JS4525', name: 'Pharmacy', nameZh: '藥劑學', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4537', code: 'JS4537', name: 'Public Health', nameZh: '公共衞生', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4542', code: 'JS4542', name: 'Chinese Medicine', nameZh: '中醫學', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4550', code: 'JS4550', name: 'Biomedical Sciences', nameZh: '生物醫學', university: '香港中文大學', category: 'Medicine' },
  { id: 'JS4601', code: 'JS4601', name: 'Bachelor of Science', nameZh: '理學士', university: '香港中文大學', category: 'Science' },
  { id: 'JS4648', code: 'JS4648', name: 'Earth and Environmental Sciences', nameZh: '地球與環境科學', university: '香港中文大學', category: 'Science' },
  { id: 'JS4682', code: 'JS4682', name: 'Enrichment Mathematics', nameZh: '數學精研', university: '香港中文大學', category: 'Science' },
  { id: 'JS4690', code: 'JS4690', name: 'Enrichment Stream in Theoretical Physics', nameZh: '理論物理精研', university: '香港中文大學', category: 'Science' },
  { id: 'JS4719', code: 'JS4719', name: 'Risk Management Science', nameZh: '風險管理科學', university: '香港中文大學', category: 'Science' },
  { id: 'JS4725', code: 'JS4725', name: 'Biotechnology, Entrepreneurship', nameZh: '生物科技、創業與醫療管理', university: '香港中文大學', category: 'Science' },
  { id: 'JS4733', code: 'JS4733', name: 'Mathematics and Information', nameZh: '數學與信息工程學', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4750', code: 'JS4750', name: 'Informatics & X Double Major', nameZh: '航天科學與地球信息學及Ｘ雙主修課程', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4760', code: 'JS4760', name: 'Interdisciplinary Data Analytics &', nameZh: '跨學科數據分析及Ｘ雙主修課程', university: '香港中文大學', category: 'Engineering' },
  { id: 'JS4801', code: 'JS4801', name: 'Bachelor of Social Science', nameZh: '社會科學學士', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4812', code: 'JS4812', name: 'Architectural Studies', nameZh: '建築學', university: '香港中文大學', category: 'Architecture & Built Environment' },
  { id: 'JS4824', code: 'JS4824', name: 'Economics', nameZh: '經濟學', university: '香港中文大學', category: 'Business' },
  { id: 'JS4836', code: 'JS4836', name: 'Geography and Resource Management', nameZh: '地理與資源管理學', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4838', code: 'JS4838', name: 'Urban Studies', nameZh: '城市研究', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4848', code: 'JS4848', name: 'Government and Public Administration', nameZh: '政治與行政學', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4850', code: 'JS4850', name: 'Journalism and Communication', nameZh: '新聞與傳播學', university: '香港中文大學', category: 'Communication & Media' },
  { id: 'JS4858', code: 'JS4858', name: 'Global Communication', nameZh: '全球傳播', university: '香港中文大學', category: 'Communication & Media' },
  { id: 'JS4862', code: 'JS4862', name: 'Psychology', nameZh: '心理學', university: '香港中文大學', category: 'Science' },
  { id: 'JS4874', code: 'JS4874', name: 'Social Work', nameZh: '社會工作', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4886', code: 'JS4886', name: 'Sociology', nameZh: '社會學', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4892', code: 'JS4892', name: 'Global Studies', nameZh: '全球研究', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4893', code: 'JS4893', name: 'Data Science and Policy Studies', nameZh: '數據科學與政策研究', university: '香港中文大學', category: 'Computer & Data Science' },
  { id: 'JS4898', code: 'JS4898', name: 'Diplomacy and International Studies', nameZh: '外交與國際事務', university: '香港中文大學', category: 'Social Science' },
  { id: 'JS4903', code: 'JS4903', name: 'Bachelor of Laws (LLB)', nameZh: '法學士', university: '香港中文大學', category: 'Law' },
  { id: 'JS5101', code: 'JS5101', name: 'International Research Enrichment', nameZh: '國際科研', university: '香港科技大學', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS5102', code: 'JS5102', name: 'Science (Group A)', nameZh: '理學Ａ組', university: '香港科技大學', category: 'Science' },
  { id: 'JS5103', code: 'JS5103', name: 'Science (Group B)', nameZh: '理學Ｂ組', university: '香港科技大學', category: 'Science' },
  { id: 'JS5118', code: 'JS5118', name: 'BSc in Biomedical and Health Sciences', nameZh: '理學士（生物醫學及健康科學）', university: '香港科技大學', category: 'Medicine' },
  { id: 'JS5181', code: 'JS5181', name: 'Science (Group A) with Extended Major in Artificial Intelligence', nameZh: '理學Ａ組– 人工智能延伸主修', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5212', code: 'JS5212', name: 'BEng in Computer Engineering', nameZh: '工學士（計算機工程學）', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5220', code: 'JS5220', name: 'Department of Chemical and Biological Engineering', nameZh: '化學及生物工程學系', university: '香港科技大學', category: 'Engineering' },
  { id: 'JS5230', code: 'JS5230', name: 'Department of Civil and Environmental Engineering', nameZh: '土木及環境工程學系', university: '香港科技大學', category: 'Engineering' },
  { id: 'JS5240', code: 'JS5240', name: 'Department of Computer Science and Engineering', nameZh: '計算機科學及工程學系', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5250', code: 'JS5250', name: 'Department of Electronic and Computer Engineering', nameZh: '電子及計算機工程學系', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5260', code: 'JS5260', name: 'Department of Industrial Engineering and Decision Analytics', nameZh: '工業工程及決策分析學系', university: '香港科技大學', category: 'Engineering' },
  { id: 'JS5270', code: 'JS5270', name: 'Department of Mechanical and Aerospace Engineering', nameZh: '機械及航空航天工程學系', university: '香港科技大學', category: 'Engineering' },
  { id: 'JS5282', code: 'JS5282', name: 'Engineering with Extended Major in Artificial Intelligence', nameZh: '工程學 – 人工智能延伸主修', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5300', code: 'JS5300', name: 'Business and Management', nameZh: '工商管理', university: '香港科技大學', category: 'Business' },
  { id: 'JS5311', code: 'JS5311', name: 'BBA in Economics', nameZh: '工商管理學士（經濟學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5312', code: 'JS5312', name: 'BBA in Finance', nameZh: '工商管理學士（金融學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5313', code: 'JS5313', name: 'BBA in Global Business', nameZh: '工商管理學士（環球商業管理）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5314', code: 'JS5314', name: 'BBA in Information Systems', nameZh: '工商管理學士（資訊系統學）', university: '香港科技大學', category: 'Computer & Data Science' },
  { id: 'JS5315', code: 'JS5315', name: 'BBA in Management', nameZh: '工商管理學士（管理學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5316', code: 'JS5316', name: 'BBA in Marketing', nameZh: '工商管理學士（市場學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5317', code: 'JS5317', name: 'BBA in Operations Management', nameZh: '工商管理學士（營運管理學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5318', code: 'JS5318', name: 'BBA in Professional Accounting', nameZh: '工商管理學士（專業會計學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5331', code: 'JS5331', name: 'BSc in Economics and Finance', nameZh: '理學士（經濟及金融學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5332', code: 'JS5332', name: 'BSc in Quantitative Finance', nameZh: '理學士（量化金融學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5411', code: 'JS5411', name: 'BSc in Global China Studies', nameZh: '理學士（環球中國研究）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5412', code: 'JS5412', name: 'BSc in Quantitative Social Analysis', nameZh: '理學士（定量社會數據分析）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5711', code: 'JS5711', name: 'BSc in Innovation, Design and Technology', nameZh: '理學士（創新設計與科技）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5811', code: 'JS5811', name: 'BSc in Biotechnology and Business', nameZh: '理學士（生物科技及商學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5812', code: 'JS5812', name: 'BSc in Environmental Management and Technology', nameZh: '理學士（環境管理及科技）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5813', code: 'JS5813', name: 'BSc in Mathematics and Economics', nameZh: '理學士（數學與經濟學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5814', code: 'JS5814', name: 'BSc in Risk Management and Business Intelligence', nameZh: '理學士（風險管理及商業智能學）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5822', code: 'JS5822', name: 'BSc in Sustainable and Green Finance', nameZh: '理學士（可持續發展及綠色金融）', university: '香港科技大學', category: 'Science' },
  { id: 'JS5901', code: 'JS5901', name: 'BEng/BSc & BBA Dual Degree Program in Technology and Management', nameZh: '科技及管理學雙學位課程', university: '香港科技大學', category: 'Science' },
  { id: 'JS6004', code: 'JS6004', name: 'Bachelor of Arts in Architectural Studies', nameZh: '建築學文學士', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6016', code: 'JS6016', name: 'Bachelor of Science in Surveying', nameZh: '理學士(測量學)', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6028', code: 'JS6028', name: 'Bachelor of Arts in Landscape Studies', nameZh: '園境學文學士', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6042', code: 'JS6042', name: 'Bachelor of Arts in Urban Studies', nameZh: '文學士(城市研究)', university: '香港大學', category: 'Social Science' },
  { id: 'JS6054', code: 'JS6054', name: 'Bachelor of Arts', nameZh: 'Bachelor of Arts', university: '香港大學', category: 'Arts' },
  { id: 'JS6066', code: 'JS6066', name: 'BA and BEd in Language Education - English', nameZh: '文學士及教育學士(語文教育)-英文教育', university: '香港大學', category: 'Education' },
  { id: 'JS6078', code: 'JS6078', name: 'Bachelor of Arts and Bachelor of Laws', nameZh: '文學士及法學士', university: '香港大學', category: 'Law' },
  { id: 'JS6080', code: 'JS6080', name: 'BA and BEd in Language Education - Chinese', nameZh: '文學士及教育學士(語文教育)-中文教育', university: '香港大學', category: 'Education' },
  { id: 'JS6092', code: 'JS6092', name: 'Bachelor of Education in Early Childhood and Special Education', nameZh: '教育學士(幼兒教育及特殊教育)', university: '香港大學', category: 'Education' },
  { id: 'JS6107', code: 'JS6107', name: 'Bachelor of Dental Surgery', nameZh: 'Bachelor of Dental Surgery', university: '香港大學', category: 'Medicine' },
  { id: 'JS6119', code: 'JS6119', name: 'Bachelor of Engineering in Data Science and Engineering', nameZh: 'Bachelor of Engineering in Data Science and Engineering', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6157', code: 'JS6157', name: 'Bachelor of Science in Speech-Language Pathology', nameZh: '理學士(言語及語言病理學)', university: '香港大學', category: 'Medicine' },
  { id: 'JS6200', code: 'JS6200', name: 'Computing and Data Science (Delta+)', nameZh: '計算與數據科學(港滬科技菁英)', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6224', code: 'JS6224', name: 'Bachelor of Arts and Sciences in Applied Artificial Intelligence', nameZh: '文理學士(應用人工智能)', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6236', code: 'JS6236', name: 'Bachelor of Arts and Sciences in Design+', nameZh: '文理學士(設計＋)', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6248', code: 'JS6248', name: 'Bachelor of Arts and Sciences in Financial Technology', nameZh: '文理學士(金融科技)', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6250', code: 'JS6250', name: 'Bachelor of Arts and Sciences in Global Health and Development', nameZh: '文理學士(環球衞生及發展)', university: '香港大學', category: 'Health Science' },
  { id: 'JS6274', code: 'JS6274', name: 'Bachelor of Arts in Global Creative Industries', nameZh: '文學士(全球創意產業)', university: '香港大學', category: 'Arts' },
  { id: 'JS6286', code: 'JS6286', name: 'Bachelor of Arts in Humanities and Digital Technologies', nameZh: 'Bachelor of Arts in Humanities and Digital Technologies', university: '香港大學', category: 'Arts' },
  { id: 'JS6298', code: 'JS6298', name: 'Bachelor of Arts and Bachelor of Engineering in AI and Data Science', nameZh: 'Bachelor of Arts and Bachelor of Engineering in AI and Data Science', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6303', code: 'JS6303', name: 'Bachelor of Engineering Elite Programme', nameZh: 'Bachelor of Engineering Elite Programme', university: '香港大學', category: 'Engineering' },
  { id: 'JS6315', code: 'JS6315', name: 'Bachelor of Engineering in Mechanical Engineering', nameZh: 'Bachelor of Engineering in Mechanical Engineering', university: '香港大學', category: 'Engineering' },
  { id: 'JS6339', code: 'JS6339', name: 'Bachelor of Engineering in Civil Engineering', nameZh: 'Bachelor of Engineering in Civil Engineering', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6353', code: 'JS6353', name: 'Bachelor of Engineering in Civil Engineering (existing)', nameZh: 'Bachelor of Engineering in Civil Engineering (existing)', university: '香港大學', category: 'Architecture & Built Environment' },
  { id: 'JS6377', code: 'JS6377', name: 'Bachelor of Engineering and Master of Science in Engineering in AI', nameZh: 'Bachelor of Engineering and Master of Science in Engineering in AI', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6406', code: 'JS6406', name: 'Bachelor of Laws', nameZh: 'Bachelor of Laws', university: '香港大學', category: 'Law' },
  { id: 'JS6418', code: 'JS6418', name: 'Bachelor of Nursing (Advanced Leadership Track)', nameZh: 'Bachelor of Nursing (Advanced Leadership Track)', university: '香港大學', category: 'Medicine' },
  { id: 'JS6717', code: 'JS6717', name: '', nameZh: '', university: '香港大學', category: 'Interdisciplinary / Broad-based' },
  { id: 'JS6729', code: 'JS6729', name: 'Bachelor of Science in Actuarial Science', nameZh: 'Bachelor of Science in Actuarial Science', university: '香港大學', category: 'Science' },
  { id: 'JS6731', code: 'JS6731', name: 'Bachelor of Social Work', nameZh: 'Bachelor of Social Work', university: '香港大學', category: 'Social Science' },
  { id: 'JS6755', code: 'JS6755', name: 'Bachelor of Business Administration', nameZh: 'Bachelor of Business Administration', university: '香港大學', category: 'Business' },
  { id: 'JS6767', code: 'JS6767', name: 'Bachelor of Economics', nameZh: 'Bachelor of Economics', university: '香港大學', category: 'Business' },
  { id: 'JS6779', code: 'JS6779', name: 'Bachelor of Science in Statistical Decision Sciences', nameZh: 'Bachelor of Science in Statistical Decision Sciences', university: '香港大學', category: 'Science' },
  { id: 'JS6781', code: 'JS6781', name: 'Bachelor of Business Administration in Accounting and Finance', nameZh: 'Bachelor of Business Administration in Accounting and Finance', university: '香港大學', category: 'Business' },
  { id: 'JS6793', code: 'JS6793', name: 'Bachelor of Business Administration (Business Analytics)', nameZh: '(', university: '香港大學', category: 'Business' },
  { id: 'JS6808', code: 'JS6808', name: 'Bachelor of Business Administration (Law) and Bachelor of Laws', nameZh: 'Bachelor of Business Administration (Law) and Bachelor of Laws', university: '香港大學', category: 'Law' },
  { id: 'JS6810', code: 'JS6810', name: 'Bachelor of Social Sciences (Government and Laws) and Bachelor of Laws', nameZh: 'Bachelor of Social Sciences (Government and Laws) and Bachelor of Laws', university: '香港大學', category: 'Law' },
  { id: 'JS6822', code: 'JS6822', name: 'Bachelor of Journalism, Media and Artificial Intelligence', nameZh: 'Bachelor of Journalism, Media and Artificial Intelligence', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS6846', code: 'JS6846', name: 'Bachelor of Science in Marketing Analytics and Technology', nameZh: 'Bachelor of Science in Marketing Analytics and Technology', university: '香港大學', category: 'Science' },
  { id: 'JS6858', code: 'JS6858', name: 'Bachelor of Science and Bachelor of Laws', nameZh: 'Bachelor of Science and Bachelor of Laws', university: '香港大學', category: 'Law' },
  { id: 'JS6860', code: 'JS6860', name: 'Bachelor of Finance in Asset Management and Private Banking', nameZh: 'Bachelor of Finance in Asset Management and Private Banking', university: '香港大學', category: 'Business' },
  { id: 'JS6884', code: 'JS6884', name: 'Bachelor of Science in Quantitative Finance', nameZh: 'Bachelor of Science in Quantitative Finance', university: '香港大學', category: 'Business' },
  { id: 'JS6896', code: 'JS6896', name: 'Bachelor of Business Administration (International Business and Global Management)', nameZh: 'Bachelor of Business Administration (International Business and Global Management)', university: '香港大學', category: 'Business' },
  { id: 'JS6901', code: 'JS6901', name: 'Bachelor of Science', nameZh: 'Bachelor of Science', university: '香港大學', category: 'Science' },
  { id: 'JS6925', code: 'JS6925', name: 'Bachelor of Engineering in Biomedical Engineering', nameZh: 'Bachelor of Engineering in Biomedical Engineering', university: '香港大學', category: 'Medicine' },
  { id: 'JS6937', code: 'JS6937', name: 'Global Engineering and Business Programme', nameZh: 'Global Engineering and Business Programme', university: '香港大學', category: 'Engineering' },
  { id: 'JS6949', code: 'JS6949', name: 'Bachelor of Biomedical Sciences', nameZh: 'Bachelor of Biomedical Sciences', university: '香港大學', category: 'Medicine' },
  { id: 'JS6987', code: 'JS6987', name: 'Bachelor of Engineering in Computer Engineering', nameZh: 'Bachelor of Engineering in Computer Engineering', university: '香港大學', category: 'Engineering' },
  { id: 'JS6999', code: 'JS6999', name: 'Bachelor of Arts and Sciences in Computing and Data Science', nameZh: 'Bachelor of Arts and Sciences in Computing and Data Science', university: '香港大學', category: 'Computer & Data Science' },
  { id: 'JS7101', code: 'JS7101', name: 'Bachelor of Arts (Honours) in Chinese', nameZh: '中文(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7123', code: 'JS7123', name: 'Bachelor of Liberal Arts (Hons) in Global Development and Sustainability', nameZh: '環球可持續發展(榮譽)博雅學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7133', code: 'JS7133', name: 'Bachelor of Arts (Honours) in Animation and Digital Arts', nameZh: '動畫及數碼藝術(榮譽)文學士', university: '嶺南大學', category: 'Design' },
  { id: 'JS7204', code: 'JS7204', name: 'Bachelor of Arts (Honours) in Translation', nameZh: '翻譯(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7211', code: 'JS7211', name: 'Bachelor of Business Administration (Honours)-Accounting and Corporate Governance', nameZh: '工商管理(榮譽)學士-會計與企業管治', university: '嶺南大學', category: 'Business' },
  { id: 'JS7212', code: 'JS7212', name: 'Bachelor of Business Administration (Honours)-Business Analytics & Innovation', nameZh: '工商管理(榮譽)學士-商業分析與創新', university: '嶺南大學', category: 'Business' },
  { id: 'JS7213', code: 'JS7213', name: 'Bachelor of Business Administration (Honours)-Finance', nameZh: '工商管理(榮譽)學士-金融', university: '嶺南大學', category: 'Business' },
  { id: 'JS7214', code: 'JS7214', name: 'Bachelor of Business Administration (Honours)-Management and Analytics', nameZh: '工商管理(榮譽)學士-管理與分析', university: '嶺南大學', category: 'Business' },
  { id: 'JS7215', code: 'JS7215', name: 'Bachelor of Business Administration (Honours)-Marketing and Social Media', nameZh: '工商管理(榮譽)學士-市場學及社交媒體', university: '嶺南大學', category: 'Communication & Media' },
  { id: 'JS7216', code: 'JS7216', name: 'Bachelor of Business Administration (Honours) in Risk and Insurance Management', nameZh: '工商管理(榮譽)學士-風險及保險管理', university: '嶺南大學', category: 'Business' },
  { id: 'JS7225', code: 'JS7225', name: 'Bachelor of Science (Honours) in Data Science', nameZh: '數據科學(榮譽)理學士', university: '嶺南大學', category: 'Computer & Data Science' },
  { id: 'JS7301', code: 'JS7301', name: 'Bachelor of Social Sciences (Honours)-Economics', nameZh: '社會科學(榮譽)學士-經濟學', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7302', code: 'JS7302', name: 'Bachelor of Social Sciences (Honours) - Government and International Affairs', nameZh: '社會科學(榮譽)學士-政府與國際事務學', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7303', code: 'JS7303', name: 'Bachelor of Social Sciences (Honours)-Psychology', nameZh: '社會科學(榮譽)學士-心理學', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7304', code: 'JS7304', name: 'Bachelor of Social Sciences (Honours)-Sociology', nameZh: '社會科學(榮譽)學士-社會學', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7305', code: 'JS7305', name: 'Bachelor of Social Sciences (Honours) - Health and Social Services Management', nameZh: '社會科學(榮譽)學士-健康及社會服務管理', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7306', code: 'JS7306', name: 'Bachelor of Social Sciences (Honours)-Social and Public Policy Studies', nameZh: '社會科學(榮譽)學士-社會與公共政策研究', university: '嶺南大學', category: 'Social Science' },
  { id: 'JS7307', code: 'JS7307', name: 'Bachelor of Social Sciences (Honours)-Social Data Science', nameZh: '社會科學(榮譽)學士-社會數據科學', university: '嶺南大學', category: 'Computer & Data Science' },
  { id: 'JS7503', code: 'JS7503', name: 'Bachelor of Arts (Honours) in English Studies', nameZh: '英語語言文學課程(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7606', code: 'JS7606', name: 'Bachelor of Arts (Honours) in Cultural Studies', nameZh: '文化研究(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7709', code: 'JS7709', name: 'Bachelor of Arts (Honours) in History', nameZh: '歷史(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7802', code: 'JS7802', name: 'Bachelor of Arts (Honours) in Philosophy', nameZh: '哲學(榮譽)文學士', university: '嶺南大學', category: 'Arts' },
  { id: 'JS7905', code: 'JS7905', name: 'Bachelor of Arts (Honours) in Film and Visual Arts', nameZh: '電影與視覺藝術(榮譽)文學士', university: '嶺南大學', category: 'Design' },
  { id: 'JS8001', code: 'JS8001', name: 'Bachelor of Arts (Honours) in Creative and Digital Arts and Bachelor of Education (Honours) (Music)', nameZh: '創意藝術與數碼藝術榮譽文學士及音樂教育榮譽學士', university: '香港教育大學', category: 'Design' },
  { id: 'JS8002', code: 'JS8002', name: 'Bachelor of Arts (Honours) in Creative and Digital Arts and Bachelor of Education (Honours) (Visual Arts)', nameZh: '創意藝術與數碼藝術榮譽文學士及視覺藝術教育榮譽學士', university: '香港教育大學', category: 'Design' },
  { id: 'JS8003', code: 'JS8003', name: 'Bachelor of Arts (Honours) in Digital Chinese Culture and Communication and Bachelor of Education (Honours) (Chinese Language)', nameZh: '數碼中國文化與傳意榮譽文學士及中文教育榮譽學士', university: '香港教育大學', category: 'Communication & Media' },
  { id: 'JS8004', code: 'JS8004', name: 'Bachelor of Arts (Honours) in English Studies and Digital Communication and Bachelor of Education (Honours) (English Language)', nameZh: '英語研究及數碼傳訊榮譽文學士及英文教育榮譽學士', university: '香港教育大學', category: 'Communication & Media' },
  { id: 'JS8005', code: 'JS8005', name: 'Bachelor of Arts (Honours) in Heritage Education and Arts Management and Bachelor of Education (Honours) (Chinese History)', nameZh: '文化傳承教育與藝術管理榮譽文學士及中國歷史教育榮譽學士', university: '香港教育大學', category: 'Education' },
  { id: 'JS8006', code: 'JS8006', name: 'Bachelor of Social Sciences (Honours) in Psychology and Bachelor of Education (Honours) (Early Childhood Education)', nameZh: '心理學榮譽社會科學學士及幼兒教育榮譽學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS8007', code: 'JS8007', name: 'Bachelor of Arts (Honours) in Personal Finance and Bachelor of Education (Honours) (Business, Accounting and Financial Studies)', nameZh: '個人理財榮譽文學士及企業、會計與財務概論教育榮譽學士', university: '香港教育大學', category: 'Education' },
  { id: 'JS8008', code: 'JS8008', name: 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology and Bachelor of Education (Honours) (Information and Communication Technology and Primary Science)', nameZh: '人工智能與教育科技榮譽理學士及資訊及通訊科技及小學科學教育榮譽學士', university: '香港教育大學', category: 'Computer & Data Science' },
  { id: 'JS8009', code: 'JS8009', name: 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology and Bachelor of Education (Honours) (Primary Mathematics)', nameZh: '人工智能與教育科技榮譽理學士及小學數學教育榮譽學士', university: '香港教育大學', category: 'Computer & Data Science' },
  { id: 'JS8010', code: 'JS8010', name: 'Bachelor of Science (Honours) in Sports Science and Coaching and Bachelor of Education (Honours) (Physical Education)', nameZh: '運動科學及教練榮譽理學士及體育教育榮譽學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS8011', code: 'JS8011', name: 'Bachelor of Science (Honours) in Integrated Environmental Management and Bachelor of Education (Honours) (Science)', nameZh: '綜合環境管理榮譽理學士及科學教育榮譽學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS8012', code: 'JS8012', name: 'Bachelor of Social Sciences (Honours) in Sociology and Community Studies and Bachelor of Education (Honours) (Geography)', nameZh: '社會學與社區研究榮譽社會科學學士及地理教育榮譽學士', university: '香港教育大學', category: 'Social Science' },
  { id: 'JS8013', code: 'JS8013', name: 'Bachelor of Social Sciences (Honours) in Sociology and Community Studies and Bachelor of Education (Honours) (Primary Humanities)', nameZh: '社會學與社區研究榮譽社會科學學士及小學人文科教育榮譽學士', university: '香港教育大學', category: 'Social Science' },
  { id: 'JS8507', code: 'JS8507', name: 'Higher Diploma in Early Childhood Education', nameZh: '幼兒教育高級文憑', university: '香港教育大學', category: 'Education' },
  { id: 'JS8651', code: 'JS8651', name: 'Bachelor of Social Sciences (Honours) in Psychology', nameZh: '心理學榮譽社會科學學士', university: '香港教育大學', category: 'Social Science' },
  { id: 'JS8663', code: 'JS8663', name: 'Bachelor of Arts (Honours) in Special Education', nameZh: '特殊教育榮譽文學士', university: '香港教育大學', category: 'Education' },
  { id: 'JS8674', code: 'JS8674', name: 'Bachelor of Arts (Honours) in Digital Chinese Culture and Communication', nameZh: '數碼中國文化與傳意榮譽文學士', university: '香港教育大學', category: 'Communication & Media' },
  { id: 'JS8675', code: 'JS8675', name: 'Bachelor of Arts (Honours) in English Studies and Digital Communication', nameZh: '英語研究及數碼傳訊榮譽文學士', university: '香港教育大學', category: 'Communication & Media' },
  { id: 'JS8685', code: 'JS8685', name: 'Bachelor of Arts (Honours) in Creative and Digital Arts (Music)', nameZh: '創意藝術與數碼藝術榮譽文學士 (音樂)', university: '香港教育大學', category: 'Design' },
  { id: 'JS8686', code: 'JS8686', name: 'Bachelor of Arts (Honours) in Creative and Digital Arts (Visual Arts)', nameZh: '創意藝術與數碼藝術榮譽文學士 (視覺藝術)', university: '香港教育大學', category: 'Design' },
  { id: 'JS8687', code: 'JS8687', name: 'Bachelor of Arts (Honours) in Heritage Education and Arts Management', nameZh: '文化傳承教育與藝術管理榮譽文學士', university: '香港教育大學', category: 'Education' },
  { id: 'JS8688', code: 'JS8688', name: 'Bachelor of Arts (Honours) in Personal Finance', nameZh: '個人理財榮譽文學士', university: '香港教育大學', category: 'Business' },
  { id: 'JS8702', code: 'JS8702', name: 'Bachelor of Science (Honours) in Integrated Environmental Management', nameZh: '綜合環境管理榮譽理學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS8714', code: 'JS8714', name: 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology', nameZh: '人工智能與教育科技榮譽理學士', university: '香港教育大學', category: 'Computer & Data Science' },
  { id: 'JS8726', code: 'JS8726', name: 'Bachelor of Science (Honours) in Sports Science and Coaching', nameZh: '運動科學及教練榮譽理學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS8727', code: 'JS8727', name: 'Bachelor of Science (Honours) in Speech Pathology and Rehabilitation', nameZh: '言語病理學及復康榮譽理學士', university: '香港教育大學', category: 'Science' },
  { id: 'JS9009', code: 'JS9009', name: 'Bachelor of Social Sciences with Honours', nameZh: '社會科學榮譽學士', university: '香港都會大學', category: 'Social Science' },
  { id: 'JS9010', code: 'JS9010', name: 'Bachelor of Social Sciences with Honours in Psychology', nameZh: '心理學榮譽社會科學學士', university: '香港都會大學', category: 'Social Science' },
  { id: 'JS9011', code: 'JS9011', name: 'Bachelor of Arts with Honours in Chinese', nameZh: '中文榮譽文學士', university: '香港都會大學', category: 'Arts' },
  { id: 'JS9013', code: 'JS9013', name: 'Bachelor of Arts with Honours in Language Studies and Translation', nameZh: '語言研究與翻譯榮譽文學士', university: '香港都會大學', category: 'Arts' },
  { id: 'JS9016', code: 'JS9016', name: 'Bachelor of Arts with Honours in Creative Advertising and Media Design', nameZh: '創意廣告及媒體設計榮譽文學士', university: '香港都會大學', category: 'Design' },
  { id: 'JS9019', code: 'JS9019', name: 'Bachelor of Arts with Honours in English Language and Culture', nameZh: '英語及文化榮譽文學士', university: '香港都會大學', category: 'Arts' },
  { id: 'JS9220', code: 'JS9220', name: 'Bachelor of Business Administration with Honours in Professional Accounting', nameZh: '專業會計榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9230', code: 'JS9230', name: 'Bachelor of Business Administration with Honours in Business Management', nameZh: '商業管理學榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9240', code: 'JS9240', name: 'Bachelor of Business Administration with Honours in Global Business', nameZh: '環球商業榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9262', code: 'JS9262', name: 'Bachelor of Business Administration with Honours in Human Resource Management', nameZh: '人力資源管理學榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9266', code: 'JS9266', name: 'Bachelor of Business Administration with Honours in Marketing', nameZh: '市場學榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9276', code: 'JS9276', name: 'Bachelor of Business Administration with Honours in Real Estate and Surveying', nameZh: '房地產及測量學榮譽工商管理學士', university: '香港都會大學', category: 'Architecture & Built Environment' },
  { id: 'JS9280', code: 'JS9280', name: 'Bachelor of Applied Psychology with Honours, Bachelor of Business Management with Honours', nameZh: '應用心理學榮譽學士，商業管理榮譽學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9291', code: 'JS9291', name: 'Bachelor of Business Administration with Honours in Sustainable Tourism and Hospitality Management', nameZh: '持續旅遊及款待管理榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9294', code: 'JS9294', name: 'Bachelor of Business Administration with Honours in Sports and eSports Management', nameZh: '運動及電競運動管理榮譽工商管理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9520', code: 'JS9520', name: 'Bachelor of Education with Honours (Putonghua and Chinese Language Education) and Bachelor of Language Studies with Honours (Chinese Linguistic Studies)', nameZh: '教育榮譽學士（普通話及中文教育）及語言研究榮譽學士（漢語語言學研究）', university: '香港都會大學', category: 'Education' },
  { id: 'JS9530', code: 'JS9530', name: 'Bachelor of Education with Honours in English Language Teaching and Bachelor of English Language Studies with Honours', nameZh: '英語教學榮譽教育學士及英語研究榮譽學士', university: '香港都會大學', category: 'Education' },
  { id: 'JS9540', code: 'JS9540', name: 'Bachelor of English Language Studies with Honours', nameZh: '英語研究榮譽學士', university: '香港都會大學', category: 'Arts' },
  { id: 'JS9550', code: 'JS9550', name: 'Bachelor of Language Studies with Honours (Applied Chinese Language Studies)', nameZh: '語言研究榮譽學士（應用中國語言）', university: '香港都會大學', category: 'Education' },
  { id: 'JS9560', code: 'JS9560', name: 'Bachelor of Education with Honours (Chinese Language Teaching) and Bachelor of Language Studies with Honours (Applied Chinese Language Studies)', nameZh: '教育榮譽學士（中國語文教學）及語言研究榮譽學士（應用中國語言）', university: '香港都會大學', category: 'Education' },
  { id: 'JS9580', code: 'JS9580', name: 'Bachelor of Education with Honours in Early Childhood Education (Leadership and Special Educational Needs)', nameZh: '教育榮譽學士（幼兒教育：領導及特殊教育需要）', university: '香港都會大學', category: 'Education' },
  { id: 'JS9719', code: 'JS9719', name: 'Bachelor of Science with Honours in Cyber and Computer Security', nameZh: '網路及電腦安全榮譽理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9720', code: 'JS9720', name: 'Bachelor of Engineering with Honours in Electronic and Computer Engineering', nameZh: '電子及電腦工程學榮譽工學士', university: '香港都會大學', category: 'Engineering' },
  { id: 'JS9731', code: 'JS9731', name: 'Bachelor of Science with Honours in Environmental Science and Green Management', nameZh: '環境科學與綠色管理榮譽理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9732', code: 'JS9732', name: 'Bachelor of Science with Honours in Biomedical Sciences and Biotechnology', nameZh: '生物醫學與生物科技榮譽理學士', university: '香港都會大學', category: 'Medicine' },
  { id: 'JS9733', code: 'JS9733', name: 'Bachelor of Science with Honours in Science (STEAM)', nameZh: '科學（STEAM）榮譽理學士', university: '香港都會大學', category: 'Science' },
  { id: 'JS9775', code: 'JS9775', name: 'Bachelor of Applied Science with Honours in Robotics and Automation Engineering', nameZh: '機器人和自動化工程榮譽應用理學士', university: '香港都會大學', category: 'Engineering' },
  { id: 'JS9776', code: 'JS9776', name: 'Bachelor of Science with Honours in Building Engineering and Management', nameZh: '建造工程與管理榮譽理學士', university: '香港都會大學', category: 'Architecture & Built Environment' },
];

export const PROGRAMME_CATEGORY_MAP = {
  'JS1000': 'Computer & Data Science',
  'JS1001': 'Science',
  'JS1002': 'Science',
  'JS1005': 'Science',
  'JS1007': 'Science',
  'JS1012': 'Business',
  'JS1013': 'Science',
  'JS1014': 'Science',
  'JS1017': 'Computer & Data Science',
  'JS1018': 'Science',
  'JS1019': 'Computer & Data Science',
  'JS1026': 'Science',
  'JS1027': 'Science',
  'JS1040': 'Design',
  'JS1041': 'Design',
  'JS1042': 'Design',
  'JS1043': 'Science',
  'JS1044': 'Science',
  'JS1050': 'Interdisciplinary / Broad-based',
  'JS1051': 'Interdisciplinary / Broad-based',
  'JS1052': 'Engineering',
  'JS1053': 'Science',
  'JS1061': 'Law',
  'JS1062': 'Law',
  'JS1070': 'Computer & Data Science',
  'JS1071': 'Computer & Data Science',
  'JS1072': 'Computer & Data Science',
  'JS1074': 'Engineering',
  'JS1102': 'Social Science',
  'JS1103': 'Arts',
  'JS1104': 'Arts',
  'JS1106': 'Communication & Media',
  'JS1108': 'Social Science',
  'JS1109': 'Arts',
  'JS1111': 'Social Science',
  'JS1112': 'Social Science',
  'JS1113': 'Social Science',
  'JS1123': 'Law',
  'JS1200': 'Interdisciplinary / Broad-based',
  'JS1201': 'Architecture & Built Environment',
  'JS1202': 'Science',
  'JS1204': 'Computer & Data Science',
  'JS1205': 'Engineering',
  'JS1206': 'Science',
  'JS1207': 'Engineering',
  'JS1208': 'Science',
  'JS1210': 'Engineering',
  'JS1211': 'Medicine',
  'JS1216': 'Engineering',
  'JS1217': 'Engineering',
  'JS1218': 'Computer & Data Science',
  'JS1219': 'Engineering',
  'JS1221': 'Computer & Data Science',
  'JS1300': 'Engineering',
  'JS1801': 'Medicine',
  'JS1805': 'Medicine',
  'JS1806': 'Science',
  'JS1807': 'Medicine',
  'JS2020': 'Arts',
  'JS2025': 'Arts',
  'JS2060': 'Arts',
  'JS2110': 'Science',
  'JS2120': 'Science',
  'JS2310': 'Science',
  'JS2330': 'Communication & Media',
  'JS2340': 'Communication & Media',
  'JS2370': 'Science',
  'JS2410': 'Medicine',
  'JS2420': 'Medicine',
  'JS2510': 'Science',
  'JS2610': 'Social Science',
  'JS2620': 'Education',
  'JS2660': 'Social Science',
  'JS2810': 'Design',
  'JS2910': 'Science',
  'JS2920': 'Science',
  'JS2930': 'Business',
  'JS2940': 'Health Science',
  'JS2950': 'Arts',
  'JS2960': 'Science',
  'JS3000': 'Interdisciplinary / Broad-based',
  'JS3003': 'Business',
  'JS3004': 'Architecture & Built Environment',
  'JS3005': 'Engineering',
  'JS3006': 'Computer & Data Science',
  'JS3007': 'Arts',
  'JS3008': 'Science',
  'JS3011': 'Science',
  'JS3030': 'Science',
  'JS3050': 'Design',
  'JS3060': 'Science',
  'JS3070': 'Science',
  'JS3080': 'Science',
  'JS3130': 'Architecture & Built Environment',
  'JS3140': 'Engineering',
  'JS3150': 'Medicine',
  'JS3160': 'Health Science',
  'JS3170': 'Engineering',
  'JS3180': 'Computer & Data Science',
  'JS3211': 'Architecture & Built Environment',
  'JS3214': 'Architecture & Built Environment',
  'JS3220': 'Science',
  'JS3223': 'Computer & Data Science',
  'JS3236': 'Engineering',
  'JS3237': 'Engineering',
  'JS3240': 'Arts',
  'JS3242': 'Health Science',
  'JS3243': 'Science',
  'JS3250': 'Social Science',
  'JS3255': 'Science',
  'JS3290': 'Health Science',
  'JS3310': 'Science',
  'JS3320': 'Arts',
  'JS3337': 'Health Science',
  'JS3375': 'Architecture & Built Environment',
  'JS3478': 'Health Science',
  'JS3569': 'Design',
  'JS3612': 'Health Science',
  'JS3624': 'Health Science',
  'JS3636': 'Health Science',
  'JS3648': 'Health Science',
  'JS3739': 'Architecture & Built Environment',
  'JS3741': 'Engineering',
  'JS3789': 'Architecture & Built Environment',
  'JS3791': 'Architecture & Built Environment',
  'JS3868': 'Computer & Data Science',
  'JS4006': 'Arts',
  'JS4018': 'Arts',
  'JS4032': 'Arts',
  'JS4044': 'Design',
  'JS4056': 'Arts',
  'JS4068': 'Arts',
  'JS4070': 'Arts',
  'JS4082': 'Arts',
  'JS4094': 'Arts',
  'JS4100': 'Arts',
  'JS4109': 'Arts',
  'JS4111': 'Arts',
  'JS4123': 'Arts',
  'JS4136': 'Arts',
  'JS4202': 'Science',
  'JS4214': 'Business',
  'JS4226': 'Business',
  'JS4238': 'Business',
  'JS4240': 'Business',
  'JS4252': 'Business',
  'JS4254': 'Business',
  'JS4264': 'Law',
  'JS4276': 'Business',
  'JS4320': 'Science',
  'JS4329': 'Science',
  'JS4331': 'Education',
  'JS4343': 'Education',
  'JS4361': 'Science',
  'JS4372': 'Education',
  'JS4386': 'Science',
  'JS4408': 'Engineering',
  'JS4412': 'Computer & Data Science',
  'JS4416': 'Computer & Data Science',
  'JS4428': 'Computer & Data Science',
  'JS4434': 'Engineering',
  'JS4446': 'Computer & Data Science',
  'JS4458': 'Engineering',
  'JS4460': 'Medicine',
  'JS4462': 'Engineering',
  'JS4468': 'Computer & Data Science',
  'JS4470': 'Engineering',
  'JS4501': 'Medicine',
  'JS4502': 'Medicine',
  'JS4513': 'Medicine',
  'JS4525': 'Medicine',
  'JS4537': 'Medicine',
  'JS4542': 'Medicine',
  'JS4550': 'Medicine',
  'JS4601': 'Science',
  'JS4648': 'Science',
  'JS4682': 'Science',
  'JS4690': 'Science',
  'JS4719': 'Science',
  'JS4725': 'Science',
  'JS4733': 'Engineering',
  'JS4750': 'Engineering',
  'JS4760': 'Engineering',
  'JS4801': 'Social Science',
  'JS4812': 'Architecture & Built Environment',
  'JS4824': 'Business',
  'JS4836': 'Social Science',
  'JS4838': 'Social Science',
  'JS4848': 'Social Science',
  'JS4850': 'Communication & Media',
  'JS4858': 'Communication & Media',
  'JS4862': 'Science',
  'JS4874': 'Social Science',
  'JS4886': 'Social Science',
  'JS4892': 'Social Science',
  'JS4893': 'Computer & Data Science',
  'JS4898': 'Social Science',
  'JS4903': 'Law',
  'JS5101': 'Interdisciplinary / Broad-based',
  'JS5102': 'Science',
  'JS5103': 'Science',
  'JS5118': 'Medicine',
  'JS5181': 'Computer & Data Science',
  'JS5212': 'Computer & Data Science',
  'JS5220': 'Engineering',
  'JS5230': 'Engineering',
  'JS5240': 'Computer & Data Science',
  'JS5250': 'Computer & Data Science',
  'JS5260': 'Engineering',
  'JS5270': 'Engineering',
  'JS5282': 'Computer & Data Science',
  'JS5300': 'Business',
  'JS5311': 'Science',
  'JS5312': 'Science',
  'JS5313': 'Science',
  'JS5314': 'Computer & Data Science',
  'JS5315': 'Science',
  'JS5316': 'Science',
  'JS5317': 'Science',
  'JS5318': 'Science',
  'JS5331': 'Science',
  'JS5332': 'Science',
  'JS5411': 'Science',
  'JS5412': 'Science',
  'JS5711': 'Science',
  'JS5811': 'Science',
  'JS5812': 'Science',
  'JS5813': 'Science',
  'JS5814': 'Science',
  'JS5822': 'Science',
  'JS5901': 'Science',
  'JS6004': 'Architecture & Built Environment',
  'JS6016': 'Architecture & Built Environment',
  'JS6028': 'Architecture & Built Environment',
  'JS6042': 'Social Science',
  'JS6054': 'Arts',
  'JS6066': 'Education',
  'JS6078': 'Law',
  'JS6080': 'Education',
  'JS6092': 'Education',
  'JS6107': 'Medicine',
  'JS6119': 'Computer & Data Science',
  'JS6157': 'Medicine',
  'JS6200': 'Computer & Data Science',
  'JS6224': 'Computer & Data Science',
  'JS6236': 'Architecture & Built Environment',
  'JS6248': 'Computer & Data Science',
  'JS6250': 'Health Science',
  'JS6274': 'Arts',
  'JS6286': 'Arts',
  'JS6298': 'Computer & Data Science',
  'JS6303': 'Engineering',
  'JS6315': 'Engineering',
  'JS6339': 'Architecture & Built Environment',
  'JS6353': 'Architecture & Built Environment',
  'JS6377': 'Computer & Data Science',
  'JS6406': 'Law',
  'JS6418': 'Medicine',
  'JS6717': 'Interdisciplinary / Broad-based',
  'JS6729': 'Science',
  'JS6731': 'Social Science',
  'JS6755': 'Business',
  'JS6767': 'Business',
  'JS6779': 'Science',
  'JS6781': 'Business',
  'JS6793': 'Business',
  'JS6808': 'Law',
  'JS6810': 'Law',
  'JS6822': 'Computer & Data Science',
  'JS6846': 'Science',
  'JS6858': 'Law',
  'JS6860': 'Business',
  'JS6884': 'Business',
  'JS6896': 'Business',
  'JS6901': 'Science',
  'JS6925': 'Medicine',
  'JS6937': 'Engineering',
  'JS6949': 'Medicine',
  'JS6987': 'Engineering',
  'JS6999': 'Computer & Data Science',
  'JS7101': 'Arts',
  'JS7123': 'Arts',
  'JS7133': 'Design',
  'JS7204': 'Arts',
  'JS7211': 'Business',
  'JS7212': 'Business',
  'JS7213': 'Business',
  'JS7214': 'Business',
  'JS7215': 'Communication & Media',
  'JS7216': 'Business',
  'JS7225': 'Computer & Data Science',
  'JS7301': 'Social Science',
  'JS7302': 'Social Science',
  'JS7303': 'Social Science',
  'JS7304': 'Social Science',
  'JS7305': 'Social Science',
  'JS7306': 'Social Science',
  'JS7307': 'Computer & Data Science',
  'JS7503': 'Arts',
  'JS7606': 'Arts',
  'JS7709': 'Arts',
  'JS7802': 'Arts',
  'JS7905': 'Design',
  'JS8001': 'Design',
  'JS8002': 'Design',
  'JS8003': 'Communication & Media',
  'JS8004': 'Communication & Media',
  'JS8005': 'Education',
  'JS8006': 'Science',
  'JS8007': 'Education',
  'JS8008': 'Computer & Data Science',
  'JS8009': 'Computer & Data Science',
  'JS8010': 'Science',
  'JS8011': 'Science',
  'JS8012': 'Social Science',
  'JS8013': 'Social Science',
  'JS8507': 'Education',
  'JS8651': 'Social Science',
  'JS8663': 'Education',
  'JS8674': 'Communication & Media',
  'JS8675': 'Communication & Media',
  'JS8685': 'Design',
  'JS8686': 'Design',
  'JS8687': 'Education',
  'JS8688': 'Business',
  'JS8702': 'Science',
  'JS8714': 'Computer & Data Science',
  'JS8726': 'Science',
  'JS8727': 'Science',
  'JS9009': 'Social Science',
  'JS9010': 'Social Science',
  'JS9011': 'Arts',
  'JS9013': 'Arts',
  'JS9016': 'Design',
  'JS9019': 'Arts',
  'JS9220': 'Science',
  'JS9230': 'Science',
  'JS9240': 'Science',
  'JS9262': 'Science',
  'JS9266': 'Science',
  'JS9276': 'Architecture & Built Environment',
  'JS9280': 'Science',
  'JS9291': 'Science',
  'JS9294': 'Science',
  'JS9520': 'Education',
  'JS9530': 'Education',
  'JS9540': 'Arts',
  'JS9550': 'Education',
  'JS9560': 'Education',
  'JS9580': 'Education',
  'JS9719': 'Science',
  'JS9720': 'Engineering',
  'JS9731': 'Science',
  'JS9732': 'Medicine',
  'JS9733': 'Science',
  'JS9775': 'Engineering',
  'JS9776': 'Architecture & Built Environment',
};

export function getProgrammeCategory(code, faculty = '', name = '') {
  // Direct lookup
  if (PROGRAMME_CATEGORY_MAP[code]) {
    return PROGRAMME_CATEGORY_MAP[code];
  }
  
  // Keyword matching fallback
  const text = (name + ' ' + faculty).toLowerCase();
  if (text.includes('social science') || text.includes('社會科學') || text.includes('sociology') || text.includes('社會學')) return 'Social Science';
  if (text.includes('education') || text.includes('教育')) return 'Education';
  if (text.includes('law') || text.includes('法律')) return 'Law';
  if (text.includes('medicine') || text.includes('醫學') || text.includes('nursing') || text.includes('護理')) return 'Medicine';
  if (text.includes('engineering') || text.includes('工程')) return 'Engineering';
  if (text.includes('business') || text.includes('商學') || text.includes('accounting') || text.includes('會計') || text.includes('finance') || text.includes('金融')) return 'Business';
  if (text.includes('computer') || text.includes('計算機') || text.includes('data science') || text.includes('數據科學') || text.includes('artificial intelligence') || text.includes('人工智能')) return 'Computer & Data Science';
  if (text.includes('science') || text.includes('理學')) return 'Science';
  if (text.includes('arts') || text.includes('文學') || text.includes('humanities') || text.includes('人文')) return 'Arts';
  
  return 'Interdisciplinary / Broad-based';
}
